//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUComputers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ltd_infoEntities2 : DbContext
    {
        public ltd_infoEntities2()
            : base("name=ltd_infoEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<store_all_alc> store_all_alc { get; set; }
        public virtual DbSet<store_all_asi> store_all_asi { get; set; }
        public virtual DbSet<store_all_asi_url> store_all_asi_url { get; set; }
        public virtual DbSet<store_all_dandh> store_all_dandh { get; set; }
        public virtual DbSet<store_all_synnex> store_all_synnex { get; set; }
        public virtual DbSet<store_all_synnex2> store_all_synnex2 { get; set; }
        public virtual DbSet<tb_discount_end_date> tb_discount_end_date { get; set; }
        public virtual DbSet<tb_dont_update> tb_dont_update { get; set; }
        public virtual DbSet<tb_ebay_selling> tb_ebay_selling { get; set; }
        public virtual DbSet<tb_ebay_selling_buyitnowprice_tmp> tb_ebay_selling_buyitnowprice_tmp { get; set; }
        public virtual DbSet<tb_ebay_selling_timeleft_tmp> tb_ebay_selling_timeleft_tmp { get; set; }
        public virtual DbSet<tb_etc_category> tb_etc_category { get; set; }
        public virtual DbSet<tb_lu_supercom> tb_lu_supercom { get; set; }
        public virtual DbSet<tb_other_inc> tb_other_inc { get; set; }
        public virtual DbSet<tb_other_inc_bind_price> tb_other_inc_bind_price { get; set; }
        public virtual DbSet<tb_other_inc_bind_price_tmp> tb_other_inc_bind_price_tmp { get; set; }
        public virtual DbSet<tb_other_inc_bind_price_tmp_history> tb_other_inc_bind_price_tmp_history { get; set; }
        public virtual DbSet<tb_other_inc_log> tb_other_inc_log { get; set; }
        public virtual DbSet<tb_other_inc_match_lu_sku> tb_other_inc_match_lu_sku { get; set; }
        public virtual DbSet<tb_other_inc_part_info> tb_other_inc_part_info { get; set; }
        public virtual DbSet<tb_other_inc_run_date> tb_other_inc_run_date { get; set; }
        public virtual DbSet<tb_other_inc_shopbot> tb_other_inc_shopbot { get; set; }
        public virtual DbSet<tb_other_inc_shopbot_mfp_no_exist> tb_other_inc_shopbot_mfp_no_exist { get; set; }
        public virtual DbSet<tb_other_inc_supercom_mfp_no_exist> tb_other_inc_supercom_mfp_no_exist { get; set; }
        public virtual DbSet<tb_other_inc_valid_lu_sku> tb_other_inc_valid_lu_sku { get; set; }
        public virtual DbSet<tb_part_price_change_setting> tb_part_price_change_setting { get; set; }
        public virtual DbSet<tb_product_category> tb_product_category { get; set; }
        public virtual DbSet<tb_supercom_eta> tb_supercom_eta { get; set; }
        public virtual DbSet<tb_supercom_notebook> tb_supercom_notebook { get; set; }
        public virtual DbSet<tb_supercom_store_2> tb_supercom_store_2 { get; set; }
        public virtual DbSet<tb_synnex_all_discount> tb_synnex_all_discount { get; set; }
        public virtual DbSet<tb_valid_category> tb_valid_category { get; set; }
    }
}
