//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace LUComputers
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class nicklu2Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new nicklu2Entities object using the connection string found in the 'nicklu2Entities' section of the application configuration file.
        /// </summary>
        public nicklu2Entities() : base("name=nicklu2Entities", "nicklu2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new nicklu2Entities object.
        /// </summary>
        public nicklu2Entities(string connectionString) : base(connectionString, "nicklu2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new nicklu2Entities object.
        /// </summary>
        public nicklu2Entities(EntityConnection connection) : base(connection, "nicklu2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_product> tb_product
        {
            get
            {
                if ((_tb_product == null))
                {
                    _tb_product = base.CreateObjectSet<tb_product>("tb_product");
                }
                return _tb_product;
            }
        }
        private ObjectSet<tb_product> _tb_product;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_product EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_product(tb_product tb_product)
        {
            base.AddObject("tb_product", tb_product);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="nicklu2Model", Name="tb_product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_product object.
        /// </summary>
        /// <param name="product_serial_no">Initial value of the product_serial_no property.</param>
        public static tb_product Createtb_product(global::System.Int32 product_serial_no)
        {
            tb_product tb_product = new tb_product();
            tb_product.product_serial_no = product_serial_no;
            return tb_product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 product_serial_no
        {
            get
            {
                return _product_serial_no;
            }
            set
            {
                if (_product_serial_no != value)
                {
                    Onproduct_serial_noChanging(value);
                    ReportPropertyChanging("product_serial_no");
                    _product_serial_no = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("product_serial_no");
                    Onproduct_serial_noChanged();
                }
            }
        }
        private global::System.Int32 _product_serial_no;
        partial void Onproduct_serial_noChanging(global::System.Int32 value);
        partial void Onproduct_serial_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_name
        {
            get
            {
                return _product_name;
            }
            set
            {
                Onproduct_nameChanging(value);
                ReportPropertyChanging("product_name");
                _product_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_name");
                Onproduct_nameChanged();
            }
        }
        private global::System.String _product_name;
        partial void Onproduct_nameChanging(global::System.String value);
        partial void Onproduct_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_short_name
        {
            get
            {
                return _product_short_name;
            }
            set
            {
                Onproduct_short_nameChanging(value);
                ReportPropertyChanging("product_short_name");
                _product_short_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_short_name");
                Onproduct_short_nameChanged();
            }
        }
        private global::System.String _product_short_name;
        partial void Onproduct_short_nameChanging(global::System.String value);
        partial void Onproduct_short_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_store_sum
        {
            get
            {
                return _product_store_sum;
            }
            set
            {
                Onproduct_store_sumChanging(value);
                ReportPropertyChanging("product_store_sum");
                _product_store_sum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_store_sum");
                Onproduct_store_sumChanged();
            }
        }
        private Nullable<global::System.Int32> _product_store_sum;
        partial void Onproduct_store_sumChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_store_sumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_sale_sum
        {
            get
            {
                return _product_sale_sum;
            }
            set
            {
                Onproduct_sale_sumChanging(value);
                ReportPropertyChanging("product_sale_sum");
                _product_sale_sum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_sale_sum");
                Onproduct_sale_sumChanged();
            }
        }
        private Nullable<global::System.Int32> _product_sale_sum;
        partial void Onproduct_sale_sumChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_sale_sumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> menu_child_serial_no
        {
            get
            {
                return _menu_child_serial_no;
            }
            set
            {
                Onmenu_child_serial_noChanging(value);
                ReportPropertyChanging("menu_child_serial_no");
                _menu_child_serial_no = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("menu_child_serial_no");
                Onmenu_child_serial_noChanged();
            }
        }
        private Nullable<global::System.Int32> _menu_child_serial_no;
        partial void Onmenu_child_serial_noChanging(Nullable<global::System.Int32> value);
        partial void Onmenu_child_serial_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_filename
        {
            get
            {
                return _product_filename;
            }
            set
            {
                Onproduct_filenameChanging(value);
                ReportPropertyChanging("product_filename");
                _product_filename = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_filename");
                Onproduct_filenameChanged();
            }
        }
        private global::System.String _product_filename;
        partial void Onproduct_filenameChanging(global::System.String value);
        partial void Onproduct_filenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> tag
        {
            get
            {
                return _tag;
            }
            set
            {
                OntagChanging(value);
                ReportPropertyChanging("tag");
                _tag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tag");
                OntagChanged();
            }
        }
        private Nullable<global::System.SByte> _tag;
        partial void OntagChanging(Nullable<global::System.SByte> value);
        partial void OntagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> product_current_real_cost
        {
            get
            {
                return _product_current_real_cost;
            }
            set
            {
                Onproduct_current_real_costChanging(value);
                ReportPropertyChanging("product_current_real_cost");
                _product_current_real_cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_current_real_cost");
                Onproduct_current_real_costChanged();
            }
        }
        private Nullable<global::System.Decimal> _product_current_real_cost;
        partial void Onproduct_current_real_costChanging(Nullable<global::System.Decimal> value);
        partial void Onproduct_current_real_costChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> product_current_special_cash_price
        {
            get
            {
                return _product_current_special_cash_price;
            }
            set
            {
                Onproduct_current_special_cash_priceChanging(value);
                ReportPropertyChanging("product_current_special_cash_price");
                _product_current_special_cash_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_current_special_cash_price");
                Onproduct_current_special_cash_priceChanged();
            }
        }
        private Nullable<global::System.Decimal> _product_current_special_cash_price;
        partial void Onproduct_current_special_cash_priceChanging(Nullable<global::System.Decimal> value);
        partial void Onproduct_current_special_cash_priceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> product_current_price
        {
            get
            {
                return _product_current_price;
            }
            set
            {
                Onproduct_current_priceChanging(value);
                ReportPropertyChanging("product_current_price");
                _product_current_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_current_price");
                Onproduct_current_priceChanged();
            }
        }
        private Nullable<global::System.Decimal> _product_current_price;
        partial void Onproduct_current_priceChanging(Nullable<global::System.Decimal> value);
        partial void Onproduct_current_priceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> product_current_cost
        {
            get
            {
                return _product_current_cost;
            }
            set
            {
                Onproduct_current_costChanging(value);
                ReportPropertyChanging("product_current_cost");
                _product_current_cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_current_cost");
                Onproduct_current_costChanged();
            }
        }
        private Nullable<global::System.Decimal> _product_current_cost;
        partial void Onproduct_current_costChanging(Nullable<global::System.Decimal> value);
        partial void Onproduct_current_costChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> product_ship_price
        {
            get
            {
                return _product_ship_price;
            }
            set
            {
                Onproduct_ship_priceChanging(value);
                ReportPropertyChanging("product_ship_price");
                _product_ship_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_ship_price");
                Onproduct_ship_priceChanged();
            }
        }
        private Nullable<global::System.Decimal> _product_ship_price;
        partial void Onproduct_ship_priceChanging(Nullable<global::System.Decimal> value);
        partial void Onproduct_ship_priceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String producter_url
        {
            get
            {
                return _producter_url;
            }
            set
            {
                Onproducter_urlChanging(value);
                ReportPropertyChanging("producter_url");
                _producter_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("producter_url");
                Onproducter_urlChanged();
            }
        }
        private global::System.String _producter_url;
        partial void Onproducter_urlChanging(global::System.String value);
        partial void Onproducter_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_order
        {
            get
            {
                return _product_order;
            }
            set
            {
                Onproduct_orderChanging(value);
                ReportPropertyChanging("product_order");
                _product_order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_order");
                Onproduct_orderChanged();
            }
        }
        private Nullable<global::System.Int32> _product_order;
        partial void Onproduct_orderChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_orderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String supplier_sku
        {
            get
            {
                return _supplier_sku;
            }
            set
            {
                Onsupplier_skuChanging(value);
                ReportPropertyChanging("supplier_sku");
                _supplier_sku = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("supplier_sku");
                Onsupplier_skuChanged();
            }
        }
        private global::System.String _supplier_sku;
        partial void Onsupplier_skuChanging(global::System.String value);
        partial void Onsupplier_skuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String manufacturer_part_number
        {
            get
            {
                return _manufacturer_part_number;
            }
            set
            {
                Onmanufacturer_part_numberChanging(value);
                ReportPropertyChanging("manufacturer_part_number");
                _manufacturer_part_number = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("manufacturer_part_number");
                Onmanufacturer_part_numberChanged();
            }
        }
        private global::System.String _manufacturer_part_number;
        partial void Onmanufacturer_part_numberChanging(global::System.String value);
        partial void Onmanufacturer_part_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ltd_stock
        {
            get
            {
                return _ltd_stock;
            }
            set
            {
                Onltd_stockChanging(value);
                ReportPropertyChanging("ltd_stock");
                _ltd_stock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ltd_stock");
                Onltd_stockChanged();
            }
        }
        private Nullable<global::System.Int32> _ltd_stock;
        partial void Onltd_stockChanging(Nullable<global::System.Int32> value);
        partial void Onltd_stockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_sale_sum_2
        {
            get
            {
                return _product_sale_sum_2;
            }
            set
            {
                Onproduct_sale_sum_2Changing(value);
                ReportPropertyChanging("product_sale_sum_2");
                _product_sale_sum_2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_sale_sum_2");
                Onproduct_sale_sum_2Changed();
            }
        }
        private Nullable<global::System.Int32> _product_sale_sum_2;
        partial void Onproduct_sale_sum_2Changing(Nullable<global::System.Int32> value);
        partial void Onproduct_sale_sum_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> product_current_cost_2
        {
            get
            {
                return _product_current_cost_2;
            }
            set
            {
                Onproduct_current_cost_2Changing(value);
                ReportPropertyChanging("product_current_cost_2");
                _product_current_cost_2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_current_cost_2");
                Onproduct_current_cost_2Changed();
            }
        }
        private Nullable<global::System.Decimal> _product_current_cost_2;
        partial void Onproduct_current_cost_2Changing(Nullable<global::System.Decimal> value);
        partial void Onproduct_current_cost_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_ship_price_2
        {
            get
            {
                return _product_ship_price_2;
            }
            set
            {
                Onproduct_ship_price_2Changing(value);
                ReportPropertyChanging("product_ship_price_2");
                _product_ship_price_2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_ship_price_2");
                Onproduct_ship_price_2Changed();
            }
        }
        private Nullable<global::System.Int32> _product_ship_price_2;
        partial void Onproduct_ship_price_2Changing(Nullable<global::System.Int32> value);
        partial void Onproduct_ship_price_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_ebay_name_2
        {
            get
            {
                return _product_ebay_name_2;
            }
            set
            {
                Onproduct_ebay_name_2Changing(value);
                ReportPropertyChanging("product_ebay_name_2");
                _product_ebay_name_2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_ebay_name_2");
                Onproduct_ebay_name_2Changed();
            }
        }
        private global::System.String _product_ebay_name_2;
        partial void Onproduct_ebay_name_2Changing(global::System.String value);
        partial void Onproduct_ebay_name_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_ebay_name
        {
            get
            {
                return _product_ebay_name;
            }
            set
            {
                Onproduct_ebay_nameChanging(value);
                ReportPropertyChanging("product_ebay_name");
                _product_ebay_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_ebay_name");
                Onproduct_ebay_nameChanged();
            }
        }
        private global::System.String _product_ebay_name;
        partial void Onproduct_ebay_nameChanging(global::System.String value);
        partial void Onproduct_ebay_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_short_name_f
        {
            get
            {
                return _product_short_name_f;
            }
            set
            {
                Onproduct_short_name_fChanging(value);
                ReportPropertyChanging("product_short_name_f");
                _product_short_name_f = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_short_name_f");
                Onproduct_short_name_fChanged();
            }
        }
        private global::System.String _product_short_name_f;
        partial void Onproduct_short_name_fChanging(global::System.String value);
        partial void Onproduct_short_name_fChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> hot
        {
            get
            {
                return _hot;
            }
            set
            {
                OnhotChanging(value);
                ReportPropertyChanging("hot");
                _hot = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hot");
                OnhotChanged();
            }
        }
        private Nullable<global::System.SByte> _hot;
        partial void OnhotChanging(Nullable<global::System.SByte> value);
        partial void OnhotChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> @new
        {
            get
            {
                return _new;
            }
            set
            {
                OnnewChanging(value);
                ReportPropertyChanging("new");
                _new = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("new");
                OnnewChanged();
            }
        }
        private Nullable<global::System.SByte> _new;
        partial void OnnewChanging(Nullable<global::System.SByte> value);
        partial void OnnewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> producter_serial_no_bak
        {
            get
            {
                return _producter_serial_no_bak;
            }
            set
            {
                Onproducter_serial_no_bakChanging(value);
                ReportPropertyChanging("producter_serial_no_bak");
                _producter_serial_no_bak = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("producter_serial_no_bak");
                Onproducter_serial_no_bakChanged();
            }
        }
        private Nullable<global::System.Int32> _producter_serial_no_bak;
        partial void Onproducter_serial_no_bakChanging(Nullable<global::System.Int32> value);
        partial void Onproducter_serial_no_bakChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> product_compatibility
        {
            get
            {
                return _product_compatibility;
            }
            set
            {
                Onproduct_compatibilityChanging(value);
                ReportPropertyChanging("product_compatibility");
                _product_compatibility = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_compatibility");
                Onproduct_compatibilityChanged();
            }
        }
        private Nullable<global::System.SByte> _product_compatibility;
        partial void Onproduct_compatibilityChanging(Nullable<global::System.SByte> value);
        partial void Onproduct_compatibilityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> split_line
        {
            get
            {
                return _split_line;
            }
            set
            {
                Onsplit_lineChanging(value);
                ReportPropertyChanging("split_line");
                _split_line = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("split_line");
                Onsplit_lineChanged();
            }
        }
        private Nullable<global::System.SByte> _split_line;
        partial void Onsplit_lineChanging(Nullable<global::System.SByte> value);
        partial void Onsplit_lineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_name_long_en
        {
            get
            {
                return _product_name_long_en;
            }
            set
            {
                Onproduct_name_long_enChanging(value);
                ReportPropertyChanging("product_name_long_en");
                _product_name_long_en = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_name_long_en");
                Onproduct_name_long_enChanged();
            }
        }
        private global::System.String _product_name_long_en;
        partial void Onproduct_name_long_enChanging(global::System.String value);
        partial void Onproduct_name_long_enChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String shopbot_info
        {
            get
            {
                return _shopbot_info;
            }
            set
            {
                Onshopbot_infoChanging(value);
                ReportPropertyChanging("shopbot_info");
                _shopbot_info = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("shopbot_info");
                Onshopbot_infoChanged();
            }
        }
        private global::System.String _shopbot_info;
        partial void Onshopbot_infoChanging(global::System.String value);
        partial void Onshopbot_infoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> product_img_sum
        {
            get
            {
                return _product_img_sum;
            }
            set
            {
                Onproduct_img_sumChanging(value);
                ReportPropertyChanging("product_img_sum");
                _product_img_sum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_img_sum");
                Onproduct_img_sumChanged();
            }
        }
        private Nullable<global::System.SByte> _product_img_sum;
        partial void Onproduct_img_sumChanging(Nullable<global::System.SByte> value);
        partial void Onproduct_img_sumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> product_size_id
        {
            get
            {
                return _product_size_id;
            }
            set
            {
                Onproduct_size_idChanging(value);
                ReportPropertyChanging("product_size_id");
                _product_size_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_size_id");
                Onproduct_size_idChanged();
            }
        }
        private Nullable<global::System.Int32> _product_size_id;
        partial void Onproduct_size_idChanging(Nullable<global::System.Int32> value);
        partial void Onproduct_size_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.SByte> is_non
        {
            get
            {
                return _is_non;
            }
            set
            {
                Onis_nonChanging(value);
                ReportPropertyChanging("is_non");
                _is_non = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_non");
                Onis_nonChanged();
            }
        }
        private Nullable<global::System.SByte> _is_non;
        partial void Onis_nonChanging(Nullable<global::System.SByte> value);
        partial void Onis_nonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String keywords
        {
            get
            {
                return _keywords;
            }
            set
            {
                OnkeywordsChanging(value);
                ReportPropertyChanging("keywords");
                _keywords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("keywords");
                OnkeywordsChanged();
            }
        }
        private global::System.String _keywords;
        partial void OnkeywordsChanging(global::System.String value);
        partial void OnkeywordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String shortcomment
        {
            get
            {
                return _shortcomment;
            }
            set
            {
                OnshortcommentChanging(value);
                ReportPropertyChanging("shortcomment");
                _shortcomment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("shortcomment");
                OnshortcommentChanged();
            }
        }
        private global::System.String _shortcomment;
        partial void OnshortcommentChanging(global::System.String value);
        partial void OnshortcommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comment
        {
            get
            {
                return _comment;
            }
            set
            {
                OncommentChanging(value);
                ReportPropertyChanging("comment");
                _comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comment");
                OncommentChanged();
            }
        }
        private global::System.String _comment;
        partial void OncommentChanging(global::System.String value);
        partial void OncommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String producter_serial_no
        {
            get
            {
                return _producter_serial_no;
            }
            set
            {
                Onproducter_serial_noChanging(value);
                ReportPropertyChanging("producter_serial_no");
                _producter_serial_no = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("producter_serial_no");
                Onproducter_serial_noChanged();
            }
        }
        private global::System.String _producter_serial_no;
        partial void Onproducter_serial_noChanging(global::System.String value);
        partial void Onproducter_serial_noChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> old_db_id
        {
            get
            {
                return _old_db_id;
            }
            set
            {
                Onold_db_idChanging(value);
                ReportPropertyChanging("old_db_id");
                _old_db_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("old_db_id");
                Onold_db_idChanged();
            }
        }
        private Nullable<global::System.Int32> _old_db_id;
        partial void Onold_db_idChanging(Nullable<global::System.Int32> value);
        partial void Onold_db_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agent_stock
        {
            get
            {
                return _agent_stock;
            }
            set
            {
                Onagent_stockChanging(value);
                ReportPropertyChanging("agent_stock");
                _agent_stock = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agent_stock");
                Onagent_stockChanged();
            }
        }
        private global::System.String _agent_stock;
        partial void Onagent_stockChanging(global::System.String value);
        partial void Onagent_stockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> regdate
        {
            get
            {
                return _regdate;
            }
            set
            {
                OnregdateChanging(value);
                ReportPropertyChanging("regdate");
                _regdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("regdate");
                OnregdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _regdate;
        partial void OnregdateChanging(Nullable<global::System.DateTime> value);
        partial void OnregdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> other_product_sku
        {
            get
            {
                return _other_product_sku;
            }
            set
            {
                Onother_product_skuChanging(value);
                ReportPropertyChanging("other_product_sku");
                _other_product_sku = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("other_product_sku");
                Onother_product_skuChanged();
            }
        }
        private Nullable<global::System.Int32> _other_product_sku;
        partial void Onother_product_skuChanging(Nullable<global::System.Int32> value);
        partial void Onother_product_skuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> category_idss
        {
            get
            {
                return _category_idss;
            }
            set
            {
                Oncategory_idssChanging(value);
                ReportPropertyChanging("category_idss");
                _category_idss = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("category_idss");
                Oncategory_idssChanged();
            }
        }
        private Nullable<global::System.Int32> _category_idss;
        partial void Oncategory_idssChanging(Nullable<global::System.Int32> value);
        partial void Oncategory_idssChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> export
        {
            get
            {
                return _export;
            }
            set
            {
                OnexportChanging(value);
                ReportPropertyChanging("export");
                _export = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("export");
                OnexportChanged();
            }
        }
        private Nullable<global::System.Boolean> _export;
        partial void OnexportChanging(Nullable<global::System.Boolean> value);
        partial void OnexportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> product_current_discount
        {
            get
            {
                return _product_current_discount;
            }
            set
            {
                Onproduct_current_discountChanging(value);
                ReportPropertyChanging("product_current_discount");
                _product_current_discount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("product_current_discount");
                Onproduct_current_discountChanged();
            }
        }
        private Nullable<global::System.Decimal> _product_current_discount;
        partial void Onproduct_current_discountChanging(Nullable<global::System.Decimal> value);
        partial void Onproduct_current_discountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> last_regdate
        {
            get
            {
                return _last_regdate;
            }
            set
            {
                Onlast_regdateChanging(value);
                ReportPropertyChanging("last_regdate");
                _last_regdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("last_regdate");
                Onlast_regdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _last_regdate;
        partial void Onlast_regdateChanging(Nullable<global::System.DateTime> value);
        partial void Onlast_regdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> part_ebay_cost
        {
            get
            {
                return _part_ebay_cost;
            }
            set
            {
                Onpart_ebay_costChanging(value);
                ReportPropertyChanging("part_ebay_cost");
                _part_ebay_cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("part_ebay_cost");
                Onpart_ebay_costChanged();
            }
        }
        private Nullable<global::System.Decimal> _part_ebay_cost;
        partial void Onpart_ebay_costChanging(Nullable<global::System.Decimal> value);
        partial void Onpart_ebay_costChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> part_ebay_price
        {
            get
            {
                return _part_ebay_price;
            }
            set
            {
                Onpart_ebay_priceChanging(value);
                ReportPropertyChanging("part_ebay_price");
                _part_ebay_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("part_ebay_price");
                Onpart_ebay_priceChanged();
            }
        }
        private Nullable<global::System.Decimal> _part_ebay_price;
        partial void Onpart_ebay_priceChanging(Nullable<global::System.Decimal> value);
        partial void Onpart_ebay_priceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> real_cost_regdate
        {
            get
            {
                return _real_cost_regdate;
            }
            set
            {
                Onreal_cost_regdateChanging(value);
                ReportPropertyChanging("real_cost_regdate");
                _real_cost_regdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("real_cost_regdate");
                Onreal_cost_regdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _real_cost_regdate;
        partial void Onreal_cost_regdateChanging(Nullable<global::System.DateTime> value);
        partial void Onreal_cost_regdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> issue
        {
            get
            {
                return _issue;
            }
            set
            {
                OnissueChanging(value);
                ReportPropertyChanging("issue");
                _issue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("issue");
                OnissueChanged();
            }
        }
        private Nullable<global::System.Boolean> _issue;
        partial void OnissueChanging(Nullable<global::System.Boolean> value);
        partial void OnissueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> view_count
        {
            get
            {
                return _view_count;
            }
            set
            {
                Onview_countChanging(value);
                ReportPropertyChanging("view_count");
                _view_count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("view_count");
                Onview_countChanged();
            }
        }
        private Nullable<global::System.Int32> _view_count;
        partial void Onview_countChanging(Nullable<global::System.Int32> value);
        partial void Onview_countChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String model
        {
            get
            {
                return _model;
            }
            set
            {
                OnmodelChanging(value);
                ReportPropertyChanging("model");
                _model = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("model");
                OnmodelChanged();
            }
        }
        private global::System.String _model;
        partial void OnmodelChanging(global::System.String value);
        partial void OnmodelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String split_name
        {
            get
            {
                return _split_name;
            }
            set
            {
                Onsplit_nameChanging(value);
                ReportPropertyChanging("split_name");
                _split_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("split_name");
                Onsplit_nameChanged();
            }
        }
        private global::System.String _split_name;
        partial void Onsplit_nameChanging(global::System.String value);
        partial void Onsplit_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> adjustment
        {
            get
            {
                return _adjustment;
            }
            set
            {
                OnadjustmentChanging(value);
                ReportPropertyChanging("adjustment");
                _adjustment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("adjustment");
                OnadjustmentChanged();
            }
        }
        private Nullable<global::System.Decimal> _adjustment;
        partial void OnadjustmentChanging(Nullable<global::System.Decimal> value);
        partial void OnadjustmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> adjustment_regdate
        {
            get
            {
                return _adjustment_regdate;
            }
            set
            {
                Onadjustment_regdateChanging(value);
                ReportPropertyChanging("adjustment_regdate");
                _adjustment_regdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("adjustment_regdate");
                Onadjustment_regdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _adjustment_regdate;
        partial void Onadjustment_regdateChanging(Nullable<global::System.DateTime> value);
        partial void Onadjustment_regdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> adjustment_enddate
        {
            get
            {
                return _adjustment_enddate;
            }
            set
            {
                Onadjustment_enddateChanging(value);
                ReportPropertyChanging("adjustment_enddate");
                _adjustment_enddate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("adjustment_enddate");
                Onadjustment_enddateChanged();
            }
        }
        private Nullable<global::System.DateTime> _adjustment_enddate;
        partial void Onadjustment_enddateChanging(Nullable<global::System.DateTime> value);
        partial void Onadjustment_enddateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String part_ebay_describe
        {
            get
            {
                return _part_ebay_describe;
            }
            set
            {
                Onpart_ebay_describeChanging(value);
                ReportPropertyChanging("part_ebay_describe");
                _part_ebay_describe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("part_ebay_describe");
                Onpart_ebay_describeChanged();
            }
        }
        private global::System.String _part_ebay_describe;
        partial void Onpart_ebay_describeChanging(global::System.String value);
        partial void Onpart_ebay_describeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> screen_size
        {
            get
            {
                return _screen_size;
            }
            set
            {
                Onscreen_sizeChanging(value);
                ReportPropertyChanging("screen_size");
                _screen_size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("screen_size");
                Onscreen_sizeChanged();
            }
        }
        private Nullable<global::System.Decimal> _screen_size;
        partial void Onscreen_sizeChanging(Nullable<global::System.Decimal> value);
        partial void Onscreen_sizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> price_sku
        {
            get
            {
                return _price_sku;
            }
            set
            {
                Onprice_skuChanging(value);
                ReportPropertyChanging("price_sku");
                _price_sku = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price_sku");
                Onprice_skuChanged();
            }
        }
        private Nullable<global::System.Int32> _price_sku;
        partial void Onprice_skuChanging(Nullable<global::System.Int32> value);
        partial void Onprice_skuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> price_sku_quantity
        {
            get
            {
                return _price_sku_quantity;
            }
            set
            {
                Onprice_sku_quantityChanging(value);
                ReportPropertyChanging("price_sku_quantity");
                _price_sku_quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price_sku_quantity");
                Onprice_sku_quantityChanged();
            }
        }
        private Nullable<global::System.Int32> _price_sku_quantity;
        partial void Onprice_sku_quantityChanging(Nullable<global::System.Int32> value);
        partial void Onprice_sku_quantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> curr_change_cost
        {
            get
            {
                return _curr_change_cost;
            }
            set
            {
                Oncurr_change_costChanging(value);
                ReportPropertyChanging("curr_change_cost");
                _curr_change_cost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("curr_change_cost");
                Oncurr_change_costChanged();
            }
        }
        private Nullable<global::System.Decimal> _curr_change_cost;
        partial void Oncurr_change_costChanging(Nullable<global::System.Decimal> value);
        partial void Oncurr_change_costChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> curr_change_price
        {
            get
            {
                return _curr_change_price;
            }
            set
            {
                Oncurr_change_priceChanging(value);
                ReportPropertyChanging("curr_change_price");
                _curr_change_price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("curr_change_price");
                Oncurr_change_priceChanged();
            }
        }
        private Nullable<global::System.Decimal> _curr_change_price;
        partial void Oncurr_change_priceChanging(Nullable<global::System.Decimal> value);
        partial void Oncurr_change_priceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String curr_change_ltd
        {
            get
            {
                return _curr_change_ltd;
            }
            set
            {
                Oncurr_change_ltdChanging(value);
                ReportPropertyChanging("curr_change_ltd");
                _curr_change_ltd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("curr_change_ltd");
                Oncurr_change_ltdChanged();
            }
        }
        private global::System.String _curr_change_ltd;
        partial void Oncurr_change_ltdChanging(global::System.String value);
        partial void Oncurr_change_ltdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> curr_change_quantity
        {
            get
            {
                return _curr_change_quantity;
            }
            set
            {
                Oncurr_change_quantityChanging(value);
                ReportPropertyChanging("curr_change_quantity");
                _curr_change_quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("curr_change_quantity");
                Oncurr_change_quantityChanged();
            }
        }
        private Nullable<global::System.Int32> _curr_change_quantity;
        partial void Oncurr_change_quantityChanging(Nullable<global::System.Int32> value);
        partial void Oncurr_change_quantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String curr_change_regdate
        {
            get
            {
                return _curr_change_regdate;
            }
            set
            {
                Oncurr_change_regdateChanging(value);
                ReportPropertyChanging("curr_change_regdate");
                _curr_change_regdate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("curr_change_regdate");
                Oncurr_change_regdateChanged();
            }
        }
        private global::System.String _curr_change_regdate;
        partial void Oncurr_change_regdateChanging(global::System.String value);
        partial void Oncurr_change_regdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ebay_system_short_name
        {
            get
            {
                return _ebay_system_short_name;
            }
            set
            {
                Onebay_system_short_nameChanging(value);
                ReportPropertyChanging("ebay_system_short_name");
                _ebay_system_short_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ebay_system_short_name");
                Onebay_system_short_nameChanged();
            }
        }
        private global::System.String _ebay_system_short_name;
        partial void Onebay_system_short_nameChanging(global::System.String value);
        partial void Onebay_system_short_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_modify
        {
            get
            {
                return _is_modify;
            }
            set
            {
                Onis_modifyChanging(value);
                ReportPropertyChanging("is_modify");
                _is_modify = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_modify");
                Onis_modifyChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_modify;
        partial void Onis_modifyChanging(Nullable<global::System.Boolean> value);
        partial void Onis_modifyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_top
        {
            get
            {
                return _is_top;
            }
            set
            {
                Onis_topChanging(value);
                ReportPropertyChanging("is_top");
                _is_top = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_top");
                Onis_topChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_top;
        partial void Onis_topChanging(Nullable<global::System.Boolean> value);
        partial void Onis_topChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prodType
        {
            get
            {
                return _prodType;
            }
            set
            {
                OnprodTypeChanging(value);
                ReportPropertyChanging("prodType");
                _prodType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prodType");
                OnprodTypeChanged();
            }
        }
        private global::System.String _prodType;
        partial void OnprodTypeChanging(global::System.String value);
        partial void OnprodTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String img_url
        {
            get
            {
                return _img_url;
            }
            set
            {
                Onimg_urlChanging(value);
                ReportPropertyChanging("img_url");
                _img_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("img_url");
                Onimg_urlChanged();
            }
        }
        private global::System.String _img_url;
        partial void Onimg_urlChanging(global::System.String value);
        partial void Onimg_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UPC
        {
            get
            {
                return _UPC;
            }
            set
            {
                OnUPCChanging(value);
                ReportPropertyChanging("UPC");
                _UPC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UPC");
                OnUPCChanged();
            }
        }
        private global::System.String _UPC;
        partial void OnUPCChanging(global::System.String value);
        partial void OnUPCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ETA
        {
            get
            {
                return _ETA;
            }
            set
            {
                OnETAChanging(value);
                ReportPropertyChanging("ETA");
                _ETA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ETA");
                OnETAChanged();
            }
        }
        private global::System.String _ETA;
        partial void OnETAChanging(global::System.String value);
        partial void OnETAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> weight
        {
            get
            {
                return _weight;
            }
            set
            {
                OnweightChanging(value);
                ReportPropertyChanging("weight");
                _weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("weight");
                OnweightChanged();
            }
        }
        private Nullable<global::System.Decimal> _weight;
        partial void OnweightChanging(Nullable<global::System.Decimal> value);
        partial void OnweightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String href_url
        {
            get
            {
                return _href_url;
            }
            set
            {
                Onhref_urlChanging(value);
                ReportPropertyChanging("href_url");
                _href_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("href_url");
                Onhref_urlChanged();
            }
        }
        private global::System.String _href_url;
        partial void Onhref_urlChanging(global::System.String value);
        partial void Onhref_urlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String short_name_for_sys
        {
            get
            {
                return _short_name_for_sys;
            }
            set
            {
                Onshort_name_for_sysChanging(value);
                ReportPropertyChanging("short_name_for_sys");
                _short_name_for_sys = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("short_name_for_sys");
                Onshort_name_for_sysChanged();
            }
        }
        private global::System.String _short_name_for_sys;
        partial void Onshort_name_for_sysChanging(global::System.String value);
        partial void Onshort_name_for_sysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_fixed
        {
            get
            {
                return _is_fixed;
            }
            set
            {
                Onis_fixedChanging(value);
                ReportPropertyChanging("is_fixed");
                _is_fixed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_fixed");
                Onis_fixedChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_fixed;
        partial void Onis_fixedChanging(Nullable<global::System.Boolean> value);
        partial void Onis_fixedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> for_sys
        {
            get
            {
                return _for_sys;
            }
            set
            {
                Onfor_sysChanging(value);
                ReportPropertyChanging("for_sys");
                _for_sys = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("for_sys");
                Onfor_sysChanged();
            }
        }
        private Nullable<global::System.Boolean> _for_sys;
        partial void Onfor_sysChanging(Nullable<global::System.Boolean> value);
        partial void Onfor_sysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String new_href_url
        {
            get
            {
                return _new_href_url;
            }
            set
            {
                Onnew_href_urlChanging(value);
                ReportPropertyChanging("new_href_url");
                _new_href_url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("new_href_url");
                Onnew_href_urlChanged();
            }
        }
        private global::System.String _new_href_url;
        partial void Onnew_href_urlChanging(global::System.String value);
        partial void Onnew_href_urlChanged();

        #endregion
    
    }

    #endregion
    
}
