//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUComputers
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_all_synnex2
    {
        public int id { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public Nullable<decimal> cost_promotion { get; set; }
        public string msrp { get; set; }
        public string part_sku { get; set; }
        public Nullable<decimal> normal { get; set; }
        public string store_quantity { get; set; }
        public string mfp { get; set; }
        public string mfp_name { get; set; }
        public string upc { get; set; }
        public string weight { get; set; }
        public string part_name { get; set; }
        public string long_name { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
