//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUComputers
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_all_dandh
    {
        public int id { get; set; }
        public string stock_status { get; set; }
        public Nullable<int> quantity_on_hand { get; set; }
        public string rebate_flag { get; set; }
        public string rebate_end_date { get; set; }
        public string item_number { get; set; }
        public string mfr_item_number { get; set; }
        public string upc_code { get; set; }
        public int subcategory_code { get; set; }
        public string vendor_name { get; set; }
        public decimal cost { get; set; }
        public Nullable<decimal> rebate_amount { get; set; }
        public Nullable<int> held_for_future_use { get; set; }
        public Nullable<decimal> freight { get; set; }
        public string ship_via { get; set; }
        public decimal weight { get; set; }
        public string short_description { get; set; }
        public string long_description { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
