//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUComputers
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_all_asi
    {
        public int id { get; set; }
        public int asi_sku { get; set; }
        public string itmeid { get; set; }
        public string description { get; set; }
        public string vendor { get; set; }
        public string cat { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public string weight { get; set; }
        public string size { get; set; }
        public string unit { get; set; }
        public string sub_category { get; set; }
        public string status { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public string upc { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
