//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUComputers
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_all_alc
    {
        public int id { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public string alc_sku { get; set; }
        public string description { get; set; }
        public string mfgpn { get; set; }
        public string price { get; set; }
        public Nullable<int> stock { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public string note5 { get; set; }
        public string note1 { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
