//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUComputers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_etc_category
    {
        public int serial_no { get; set; }
        public Nullable<int> etc_category_id { get; set; }
        public string etc_category_name { get; set; }
        public Nullable<int> lu_category_id { get; set; }
        public string lu_category_name { get; set; }
    }
}
