//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUComputers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_selling
    {
        public int id { get; set; }
        public Nullable<decimal> BuyItNowPrice { get; set; }
        public string BuyItNowPrice_currencyID { get; set; }
        public string ItemID { get; set; }
        public string ListingDetails_StartTime { get; set; }
        public string ListingDetails_ViewItemURL { get; set; }
        public string ListingDetails_ViewItemURLForNaturalSearch { get; set; }
        public string ListingType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> SellingStatus_CurrentPrice { get; set; }
        public string SellingStatus_CurrentPrice_currencyID { get; set; }
        public Nullable<decimal> ShippingDetails_ShippingServiceCost { get; set; }
        public string TimeLeft { get; set; }
        public string Title { get; set; }
        public Nullable<int> WatchCount { get; set; }
        public Nullable<int> QuantityAvailable { get; set; }
        public string SKU { get; set; }
        public string PictureDetails_GalleryURL { get; set; }
        public Nullable<decimal> ClassifiedAdPayPerLeadFee { get; set; }
        public System.DateTime regdate { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public Nullable<int> sys_sku { get; set; }
    }
}
