//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUComputers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_other_inc_match_lu_sku
    {
        public int id { get; set; }
        public Nullable<int> lu_sku { get; set; }
        public string other_inc_sku { get; set; }
        public Nullable<int> other_inc_type { get; set; }
        public string tmp { get; set; }
        public Nullable<bool> is_have_info { get; set; }
        public string prodType { get; set; }
    }
}
