//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUComputers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_other_inc_log
    {
        public int id { get; set; }
        public Nullable<int> ltd_id { get; set; }
        public string ltd_name { get; set; }
        public System.DateTime regdate { get; set; }
        public Nullable<int> totality { get; set; }
        public Nullable<int> new_quantity { get; set; }
        public Nullable<int> deleted_quantity { get; set; }
        public Nullable<int> hike_quantity { get; set; }
        public Nullable<int> depreciate_quantity { get; set; }
        public Nullable<int> match_totality { get; set; }
        public Nullable<int> match_new_quantity { get; set; }
        public Nullable<int> match_delete_quantity { get; set; }
        public Nullable<int> match_hike_quantity { get; set; }
        public Nullable<int> match_depreciate_quantity { get; set; }
        public string compare_table_name { get; set; }
    }
}
