//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUComputers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_other_inc_run_date
    {
        public int id { get; set; }
        public Nullable<int> other_inc_id { get; set; }
        public string db_table_name { get; set; }
        public Nullable<System.DateTime> run_date { get; set; }
    }
}
