//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUComputers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_part_price_change_setting
    {
        public int id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<decimal> cost_min { get; set; }
        public Nullable<decimal> cost_max { get; set; }
        public Nullable<int> rate { get; set; }
        public Nullable<bool> is_percent { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
