//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bughistory
    {
        public long HistoryID { get; set; }
        public int BugID { get; set; }
        public string UserName { get; set; }
        public string Action { get; set; }
        public string FullInfo { get; set; }
        public System.DateTime ActionDate { get; set; }
    }
}
