//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class buginfo
    {
        public int BugID { get; set; }
        public long ProjectID { get; set; }
        public string ProjectName { get; set; }
        public long ModuleID { get; set; }
        public string ModulePath { get; set; }
        public string BugTitle { get; set; }
        public sbyte BugSeverity { get; set; }
        public string BugType { get; set; }
        public string BugOS { get; set; }
        public string BugStatus { get; set; }
        public string LinkID { get; set; }
        public string MailTo { get; set; }
        public string OpenedBy { get; set; }
        public System.DateTime OpenedDate { get; set; }
        public string OpenedBuild { get; set; }
        public string AssignedTo { get; set; }
        public System.DateTime AssignedDate { get; set; }
        public string ResolvedBy { get; set; }
        public string Resolution { get; set; }
        public string ResolvedBuild { get; set; }
        public System.DateTime ResolvedDate { get; set; }
        public string ClosedBy { get; set; }
        public System.DateTime ClosedDate { get; set; }
        public string LastEditedBy { get; set; }
        public System.DateTime LastEditedDate { get; set; }
    }
}
