//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bugproject
    {
        public long ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDoc { get; set; }
        public string ProjectPlan { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
