//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bugquery
    {
        public long QueryID { get; set; }
        public string UserName { get; set; }
        public string QueryTitle { get; set; }
        public string QueryString { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
