//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nicklu2Entities : DbContext
    {
        public nicklu2Entities()
            : base("name=nicklu2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bugfile> bugfile { get; set; }
        public DbSet<buggroup> buggroup { get; set; }
        public DbSet<bughistory> bughistory { get; set; }
        public DbSet<buginfo> buginfo { get; set; }
        public DbSet<bugmodule> bugmodule { get; set; }
        public DbSet<bugproject> bugproject { get; set; }
        public DbSet<bugquery> bugquery { get; set; }
        public DbSet<buguser> buguser { get; set; }
        public DbSet<tb_account> tb_account { get; set; }
        public DbSet<tb_advertise> tb_advertise { get; set; }
        public DbSet<tb_advertise_page> tb_advertise_page { get; set; }
        public DbSet<tb_ask_question> tb_ask_question { get; set; }
        public DbSet<tb_business> tb_business { get; set; }
        public DbSet<tb_cart_temp> tb_cart_temp { get; set; }
        public DbSet<tb_cart_temp_price> tb_cart_temp_price { get; set; }
        public DbSet<tb_chat_msg> tb_chat_msg { get; set; }
        public DbSet<tb_compatibility> tb_compatibility { get; set; }
        public DbSet<tb_compatibility_category> tb_compatibility_category { get; set; }
        public DbSet<tb_compatibility_sum> tb_compatibility_sum { get; set; }
        public DbSet<tb_compatibility_templete> tb_compatibility_templete { get; set; }
        public DbSet<tb_computer_case> tb_computer_case { get; set; }
        public DbSet<tb_computer_cpu> tb_computer_cpu { get; set; }
        public DbSet<tb_country> tb_country { get; set; }
        public DbSet<tb_currency_convert> tb_currency_convert { get; set; }
        public DbSet<tb_currency_convert_cn> tb_currency_convert_cn { get; set; }
        public DbSet<tb_customer> tb_customer { get; set; }
        public DbSet<tb_customer_2008> tb_customer_2008 { get; set; }
        public DbSet<tb_customer_bank> tb_customer_bank { get; set; }
        public DbSet<tb_customer_copy> tb_customer_copy { get; set; }
        public DbSet<tb_customer_helper> tb_customer_helper { get; set; }
        public DbSet<tb_customer_store> tb_customer_store { get; set; }
        public DbSet<tb_customer_store_2008> tb_customer_store_2008 { get; set; }
        public DbSet<tb_customer_store_copy> tb_customer_store_copy { get; set; }
        public DbSet<tb_customer_store_tmp> tb_customer_store_tmp { get; set; }
        public DbSet<tb_customer_tmp> tb_customer_tmp { get; set; }
        public DbSet<tb_discount_end_date> tb_discount_end_date { get; set; }
        public DbSet<tb_ebay_category_and_product> tb_ebay_category_and_product { get; set; }
        public DbSet<tb_ebay_category_part_category> tb_ebay_category_part_category { get; set; }
        public DbSet<tb_ebay_code_and_luc_sku> tb_ebay_code_and_luc_sku { get; set; }
        public DbSet<tb_ebay_custom_system> tb_ebay_custom_system { get; set; }
        public DbSet<tb_ebay_etc_items> tb_ebay_etc_items { get; set; }
        public DbSet<tb_ebay_item_number> tb_ebay_item_number { get; set; }
        public DbSet<tb_ebay_part_comment> tb_ebay_part_comment { get; set; }
        public DbSet<tb_ebay_part_price_history> tb_ebay_part_price_history { get; set; }
        public DbSet<tb_ebay_promotional_items> tb_ebay_promotional_items { get; set; }
        public DbSet<tb_ebay_promotional_items_copy> tb_ebay_promotional_items_copy { get; set; }
        public DbSet<tb_ebay_promotional_sale_details> tb_ebay_promotional_sale_details { get; set; }
        public DbSet<tb_ebay_promotional_sale_id> tb_ebay_promotional_sale_id { get; set; }
        public DbSet<tb_ebay_promotional_sale_id_copy> tb_ebay_promotional_sale_id_copy { get; set; }
        public DbSet<tb_ebay_selling> tb_ebay_selling { get; set; }
        public DbSet<tb_ebay_selling_buyitnowprice_tmp> tb_ebay_selling_buyitnowprice_tmp { get; set; }
        public DbSet<tb_ebay_selling_timeleft_tmp> tb_ebay_selling_timeleft_tmp { get; set; }
        public DbSet<tb_ebay_selling_tmp_db> tb_ebay_selling_tmp_db { get; set; }
        public DbSet<tb_ebay_send_xml_history> tb_ebay_send_xml_history { get; set; }
        public DbSet<tb_ebay_send_xml_result_history> tb_ebay_send_xml_result_history { get; set; }
        public DbSet<tb_ebay_shipping_settings> tb_ebay_shipping_settings { get; set; }
        public DbSet<tb_ebay_store> tb_ebay_store { get; set; }
        public DbSet<tb_ebay_store_category> tb_ebay_store_category { get; set; }
        public DbSet<tb_ebay_store_detail> tb_ebay_store_detail { get; set; }
        public DbSet<tb_ebay_store_page> tb_ebay_store_page { get; set; }
        public DbSet<tb_ebay_store_templete> tb_ebay_store_templete { get; set; }
        public DbSet<tb_ebay_sys_create_str> tb_ebay_sys_create_str { get; set; }
        public DbSet<tb_ebay_system> tb_ebay_system { get; set; }
        public DbSet<tb_ebay_system_and_category> tb_ebay_system_and_category { get; set; }
        public DbSet<tb_ebay_system_case_group> tb_ebay_system_case_group { get; set; }
        public DbSet<tb_ebay_system_history> tb_ebay_system_history { get; set; }
        public DbSet<tb_ebay_system_item_specifics> tb_ebay_system_item_specifics { get; set; }
        public DbSet<tb_ebay_system_item_specifics_keyword> tb_ebay_system_item_specifics_keyword { get; set; }
        public DbSet<tb_ebay_system_main_comment> tb_ebay_system_main_comment { get; set; }
        public DbSet<tb_ebay_system_part_comment> tb_ebay_system_part_comment { get; set; }
        public DbSet<tb_ebay_system_part_name_keyword> tb_ebay_system_part_name_keyword { get; set; }
        public DbSet<tb_ebay_system_part_zero_price> tb_ebay_system_part_zero_price { get; set; }
        public DbSet<tb_ebay_system_parts> tb_ebay_system_parts { get; set; }
        public DbSet<tb_ebay_system_parts_history> tb_ebay_system_parts_history { get; set; }
        public DbSet<tb_ebay_system_parts_replace> tb_ebay_system_parts_replace { get; set; }
        public DbSet<tb_ebay_system_shipping> tb_ebay_system_shipping { get; set; }
        public DbSet<tb_ebay_system_warned> tb_ebay_system_warned { get; set; }
        public DbSet<tb_ebay_template_cates> tb_ebay_template_cates { get; set; }
        public DbSet<tb_ebay_templete> tb_ebay_templete { get; set; }
        public DbSet<tb_ebay_templete_and_category> tb_ebay_templete_and_category { get; set; }
        public DbSet<tb_ebay_templete_sub_summary> tb_ebay_templete_sub_summary { get; set; }
        public DbSet<tb_ebay_turbolist> tb_ebay_turbolist { get; set; }
        public DbSet<tb_email_history> tb_email_history { get; set; }
        public DbSet<tb_error_log> tb_error_log { get; set; }
        public DbSet<tb_exchange> tb_exchange { get; set; }
        public DbSet<tb_facture_state> tb_facture_state { get; set; }
        public DbSet<tb_free_back> tb_free_back { get; set; }
        public DbSet<tb_ip_deny> tb_ip_deny { get; set; }
        public DbSet<tb_keyword> tb_keyword { get; set; }
        public DbSet<tb_keyword_change> tb_keyword_change { get; set; }
        public DbSet<tb_login_log> tb_login_log { get; set; }
        public DbSet<tb_menu> tb_menu { get; set; }
        public DbSet<tb_menu_child> tb_menu_child { get; set; }
        public DbSet<tb_menu_parent> tb_menu_parent { get; set; }
        public DbSet<tb_modify_price_history> tb_modify_price_history { get; set; }
        public DbSet<tb_news> tb_news { get; set; }
        public DbSet<tb_news_letter> tb_news_letter { get; set; }
        public DbSet<tb_on_sale> tb_on_sale { get; set; }
        public DbSet<tb_on_sale_history> tb_on_sale_history { get; set; }
        public DbSet<tb_order> tb_order { get; set; }
        public DbSet<tb_order_assigned_to> tb_order_assigned_to { get; set; }
        public DbSet<tb_order_code> tb_order_code { get; set; }
        public DbSet<tb_order_ebay> tb_order_ebay { get; set; }
        public DbSet<tb_order_ebay_copy> tb_order_ebay_copy { get; set; }
        public DbSet<tb_order_ebay_quantity> tb_order_ebay_quantity { get; set; }
        public DbSet<tb_order_facture_state> tb_order_facture_state { get; set; }
        public DbSet<tb_order_helper> tb_order_helper { get; set; }
        public DbSet<tb_order_helper_2008> tb_order_helper_2008 { get; set; }
        public DbSet<tb_order_helper_copy> tb_order_helper_copy { get; set; }
        public DbSet<tb_order_helper_tmp> tb_order_helper_tmp { get; set; }
        public DbSet<tb_order_invoice> tb_order_invoice { get; set; }
        public DbSet<tb_order_invoice_temp_2008> tb_order_invoice_temp_2008 { get; set; }
        public DbSet<tb_order_invoice_void> tb_order_invoice_void { get; set; }
        public DbSet<tb_order_notepad> tb_order_notepad { get; set; }
        public DbSet<tb_order_pay_record> tb_order_pay_record { get; set; }
        public DbSet<tb_order_pay_status> tb_order_pay_status { get; set; }
        public DbSet<tb_order_paypal_error_info> tb_order_paypal_error_info { get; set; }
        public DbSet<tb_order_paypal_paymentinfo> tb_order_paypal_paymentinfo { get; set; }
        public DbSet<tb_order_paypal_record> tb_order_paypal_record { get; set; }
        public DbSet<tb_order_paypal_record_info> tb_order_paypal_record_info { get; set; }
        public DbSet<tb_order_paypal_send_info> tb_order_paypal_send_info { get; set; }
        public DbSet<tb_order_product> tb_order_product { get; set; }
        public DbSet<tb_order_product_copy> tb_order_product_copy { get; set; }
        public DbSet<tb_order_product_history> tb_order_product_history { get; set; }
        public DbSet<tb_order_product_sys_detail> tb_order_product_sys_detail { get; set; }
        public DbSet<tb_order_product_sys_detail_copy> tb_order_product_sys_detail_copy { get; set; }
        public DbSet<tb_order_product_temp> tb_order_product_temp { get; set; }
        public DbSet<tb_order_shipping_date> tb_order_shipping_date { get; set; }
        public DbSet<tb_order_system_finish_date> tb_order_system_finish_date { get; set; }
        public DbSet<tb_order_system_note> tb_order_system_note { get; set; }
        public DbSet<tb_order_total_month> tb_order_total_month { get; set; }
        public DbSet<tb_order_ups_tracking_number> tb_order_ups_tracking_number { get; set; }
        public DbSet<tb_other_inc> tb_other_inc { get; set; }
        public DbSet<tb_other_inc_bind_price> tb_other_inc_bind_price { get; set; }
        public DbSet<tb_other_inc_bind_price_tmp> tb_other_inc_bind_price_tmp { get; set; }
        public DbSet<tb_other_inc_bind_price_tmp_history> tb_other_inc_bind_price_tmp_history { get; set; }
        public DbSet<tb_other_inc_match_lu_sku> tb_other_inc_match_lu_sku { get; set; }
        public DbSet<tb_other_inc_part_info> tb_other_inc_part_info { get; set; }
        public DbSet<tb_other_inc_shopbot> tb_other_inc_shopbot { get; set; }
        public DbSet<tb_other_inc_supercom_mfp_no_exist> tb_other_inc_supercom_mfp_no_exist { get; set; }
        public DbSet<tb_other_inc_synnex> tb_other_inc_synnex { get; set; }
        public DbSet<tb_other_inc_valid_lu_sku> tb_other_inc_valid_lu_sku { get; set; }
        public DbSet<tb_page_error_info> tb_page_error_info { get; set; }
        public DbSet<tb_part_and_shipping> tb_part_and_shipping { get; set; }
        public DbSet<tb_part_app_category> tb_part_app_category { get; set; }
        public DbSet<tb_part_app_page_url> tb_part_app_page_url { get; set; }
        public DbSet<tb_part_cate_view_count> tb_part_cate_view_count { get; set; }
        public DbSet<tb_part_comment> tb_part_comment { get; set; }
        public DbSet<tb_part_compare_fields> tb_part_compare_fields { get; set; }
        public DbSet<tb_part_compare_fields_record> tb_part_compare_fields_record { get; set; }
        public DbSet<tb_part_cpu_and_comment> tb_part_cpu_and_comment { get; set; }
        public DbSet<tb_part_getin> tb_part_getin { get; set; }
        public DbSet<tb_part_getin_detail> tb_part_getin_detail { get; set; }
        public DbSet<tb_part_getin_order> tb_part_getin_order { get; set; }
        public DbSet<tb_part_group> tb_part_group { get; set; }
        public DbSet<tb_part_group_detail> tb_part_group_detail { get; set; }
        public DbSet<tb_part_keyword_analyse_word> tb_part_keyword_analyse_word { get; set; }
        public DbSet<tb_part_not_change_price> tb_part_not_change_price { get; set; }
        public DbSet<tb_part_price_change_setting> tb_part_price_change_setting { get; set; }
        public DbSet<tb_part_relation_cpu_fan> tb_part_relation_cpu_fan { get; set; }
        public DbSet<tb_part_relation_motherboard_video_audio_port> tb_part_relation_motherboard_video_audio_port { get; set; }
        public DbSet<tb_pay> tb_pay { get; set; }
        public DbSet<tb_pay_method_new> tb_pay_method_new { get; set; }
        public DbSet<tb_pay_record_method> tb_pay_record_method { get; set; }
        public DbSet<tb_pre_index_page_setting> tb_pre_index_page_setting { get; set; }
        public DbSet<tb_pre_status> tb_pre_status { get; set; }
        public DbSet<tb_product> tb_product { get; set; }
        public DbSet<tb_product_category> tb_product_category { get; set; }
        public DbSet<tb_product_category_copy> tb_product_category_copy { get; set; }
        public DbSet<tb_product_category_copy2> tb_product_category_copy2 { get; set; }
        public DbSet<tb_product_category_keyword> tb_product_category_keyword { get; set; }
        public DbSet<tb_product_category_keyword_sub> tb_product_category_keyword_sub { get; set; }
        public DbSet<tb_product_category_new> tb_product_category_new { get; set; }
        public DbSet<tb_product_cn> tb_product_cn { get; set; }
        public DbSet<tb_product_coefficient_category> tb_product_coefficient_category { get; set; }
        public DbSet<tb_product_collection> tb_product_collection { get; set; }
        public DbSet<tb_product_compatibility> tb_product_compatibility { get; set; }
        public DbSet<tb_product_compatibility_templete> tb_product_compatibility_templete { get; set; }
        public DbSet<tb_product_copy> tb_product_copy { get; set; }
        public DbSet<tb_product_del_backup> tb_product_del_backup { get; set; }
        public DbSet<tb_product_detail> tb_product_detail { get; set; }
        public DbSet<tb_product_hd> tb_product_hd { get; set; }
        public DbSet<tb_product_import_price> tb_product_import_price { get; set; }
        public DbSet<tb_product_import_price_history> tb_product_import_price_history { get; set; }
        public DbSet<tb_product_in> tb_product_in { get; set; }
        public DbSet<tb_product_line> tb_product_line { get; set; }
        public DbSet<tb_product_out> tb_product_out { get; set; }
        public DbSet<tb_product_price_history> tb_product_price_history { get; set; }
        public DbSet<tb_product_price_tmp> tb_product_price_tmp { get; set; }
        public DbSet<tb_product_shipping_fee> tb_product_shipping_fee { get; set; }
        public DbSet<tb_product_size> tb_product_size { get; set; }
        public DbSet<tb_product_split_name> tb_product_split_name { get; set; }
        public DbSet<tb_product_store_sum> tb_product_store_sum { get; set; }
        public DbSet<tb_product_temp_stock> tb_product_temp_stock { get; set; }
        public DbSet<tb_product_titles> tb_product_titles { get; set; }
        public DbSet<tb_product_virtual> tb_product_virtual { get; set; }
        public DbSet<tb_producter> tb_producter { get; set; }
        public DbSet<tb_professional> tb_professional { get; set; }
        public DbSet<tb_purchase> tb_purchase { get; set; }
        public DbSet<tb_purchase_pay> tb_purchase_pay { get; set; }
        public DbSet<tb_read_log> tb_read_log { get; set; }
        public DbSet<tb_right> tb_right { get; set; }
        public DbSet<tb_rival_store> tb_rival_store { get; set; }
        public DbSet<tb_rival_url> tb_rival_url { get; set; }
        public DbSet<tb_rule> tb_rule { get; set; }
        public DbSet<tb_sale_promotion> tb_sale_promotion { get; set; }
        public DbSet<tb_shipping_company> tb_shipping_company { get; set; }
        public DbSet<tb_sp_detail> tb_sp_detail { get; set; }
        public DbSet<tb_sp_tmp> tb_sp_tmp { get; set; }
        public DbSet<tb_sp_tmp_backup> tb_sp_tmp_backup { get; set; }
        public DbSet<tb_sp_tmp_detail> tb_sp_tmp_detail { get; set; }
        public DbSet<tb_split_line> tb_split_line { get; set; }
        public DbSet<tb_staff> tb_staff { get; set; }
        public DbSet<tb_state_shipping> tb_state_shipping { get; set; }
        public DbSet<tb_store_customer_code> tb_store_customer_code { get; set; }
        public DbSet<tb_store_order_code> tb_store_order_code { get; set; }
        public DbSet<tb_store_sys_code> tb_store_sys_code { get; set; }
        public DbSet<tb_supercom_notebook> tb_supercom_notebook { get; set; }
        public DbSet<tb_supercom_store> tb_supercom_store { get; set; }
        public DbSet<tb_supercom_store_2> tb_supercom_store_2 { get; set; }
        public DbSet<tb_sys> tb_sys { get; set; }
        public DbSet<tb_system_category> tb_system_category { get; set; }
        public DbSet<tb_system_code_store> tb_system_code_store { get; set; }
        public DbSet<tb_system_configure_category> tb_system_configure_category { get; set; }
        public DbSet<tb_system_product> tb_system_product { get; set; }
        public DbSet<tb_system_templete> tb_system_templete { get; set; }
        public DbSet<tb_system_templete_category> tb_system_templete_category { get; set; }
        public DbSet<tb_system_templete_detail> tb_system_templete_detail { get; set; }
        public DbSet<tb_temp> tb_temp { get; set; }
        public DbSet<tb_templete_replace_parameter> tb_templete_replace_parameter { get; set; }
        public DbSet<tb_timer> tb_timer { get; set; }
        public DbSet<tb_timer_href> tb_timer_href { get; set; }
        public DbSet<tb_timer_href_history> tb_timer_href_history { get; set; }
        public DbSet<tb_tmp> tb_tmp { get; set; }
        public DbSet<tb_tmp_sku> tb_tmp_sku { get; set; }
        public DbSet<tb_top> tb_top { get; set; }
        public DbSet<tb_track> tb_track { get; set; }
        public DbSet<tb_update_product_cost_history> tb_update_product_cost_history { get; set; }
        public DbSet<tb_update_product_store> tb_update_product_store { get; set; }
        public DbSet<tb_update_relation> tb_update_relation { get; set; }
        public DbSet<tb_update_table_fields> tb_update_table_fields { get; set; }
        public DbSet<tb_update_ups> tb_update_ups { get; set; }
        public DbSet<tb_vendor> tb_vendor { get; set; }
        public DbSet<tb_execute_day> tb_execute_day { get; set; }
        public DbSet<tb_other_inc_amount_date> tb_other_inc_amount_date { get; set; }
    }
}
