//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_account
    {
        public int account_id { get; set; }
        public Nullable<int> shipping_company_id { get; set; }
        public Nullable<int> product_size_id { get; set; }
        public Nullable<int> product_category { get; set; }
        public Nullable<decimal> charge { get; set; }
        public Nullable<int> qty { get; set; }
    }
}
