//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cart_temp
    {
        public int cart_temp_serial_no { get; set; }
        public Nullable<int> cart_temp_code { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<int> menu_child_serial_no { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public string ip { get; set; }
        public string customer { get; set; }
        public Nullable<int> cart_temp_Quantity { get; set; }
        public Nullable<int> customer_serial_no { get; set; }
        public Nullable<int> shipping_company { get; set; }
        public Nullable<int> state_shipping { get; set; }
        public Nullable<decimal> shipping_charge { get; set; }
        public Nullable<decimal> sale_tax { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<sbyte> is_noebook { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> old_price { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> pay_method { get; set; }
        public Nullable<System.DateTime> pick_datetime_1 { get; set; }
        public Nullable<System.DateTime> pick_datetime_2 { get; set; }
        public Nullable<decimal> save_price { get; set; }
        public Nullable<decimal> price_rate { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string shipping_state_code { get; set; }
        public string shipping_country_code { get; set; }
        public string prodType { get; set; }
        public string price_unit { get; set; }
        public Nullable<int> current_system { get; set; }
    }
}
