//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_discount_end_date
    {
        public int id { get; set; }
        public string CompanyName { get; set; }
        public string Discount { get; set; }
        public string DiscountEndDate { get; set; }
        public string MFP { get; set; }
        public string PartName { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
