//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_store_page
    {
        public int id { get; set; }
        public Nullable<int> ebay_templete_id { get; set; }
        public string ebay_templete_comment { get; set; }
        public string ebay_templete_content { get; set; }
        public string ebay_templete_content2 { get; set; }
        public string ebay_templete_top { get; set; }
        public string ebay_templete_info { get; set; }
        public Nullable<bool> is_system { get; set; }
        public string ebay_code { get; set; }
        public Nullable<decimal> ebay_price { get; set; }
        public Nullable<System.DateTime> ebay_publish_date { get; set; }
        public Nullable<int> lu_sku { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> last_regdate { get; set; }
    }
}
