//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_system_main_comment
    {
        public int id { get; set; }
        public Nullable<int> sub_id { get; set; }
        public string comm_name { get; set; }
        public string comment { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
