//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_system_item_specifics_keyword
    {
        public int Id { get; set; }
        public string Keyword { get; set; }
        public string SpecificsName { get; set; }
        public string SpecificsValue { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
    }
}
