//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_promotional_sale_details
    {
        public int Id { get; set; }
        public string SaleID { get; set; }
        public string SaleName { get; set; }
        public string SaleItemID { get; set; }
        public string Status { get; set; }
        public string DiscountType { get; set; }
        public decimal DiscountValue { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string SaleType { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
