//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_system_and_category
    {
        public int ID { get; set; }
        public Nullable<int> eBaySysCategoryID { get; set; }
        public Nullable<int> SystemSku { get; set; }
    }
}
