//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_store
    {
        public int id { get; set; }
        public string ebay_store_comment { get; set; }
        public string ebay_code { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> is_modify_price { get; set; }
        public Nullable<sbyte> ebay_store_type { get; set; }
        public Nullable<bool> is_templete { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> last_regdate { get; set; }
        public Nullable<int> lu_ebay_sku { get; set; }
    }
}
