//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_template_cates
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Logo1 { get; set; }
        public string Logo2 { get; set; }
        public bool showit { get; set; }
        public string ToUrl { get; set; }
        public int Priority { get; set; }
    }
}
