//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_system_parts_replace
    {
        public int id { get; set; }
        public Nullable<int> system_sku { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public Nullable<int> comment_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> part_group_id { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
