//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_custom_system
    {
        public int ebay_system_custom_id { get; set; }
        public string ebay_client_first_name { get; set; }
        public string ebay_client_last_name { get; set; }
        public string ebay_client_email { get; set; }
        public string ebay_client_ip { get; set; }
        public string ebay_client_note { get; set; }
        public string ebay_client_phone { get; set; }
        public string system_code { get; set; }
        public string old_system_templete_serial_no { get; set; }
        public string new_system_templete_serial_no { get; set; }
        public string create_system_staff { get; set; }
        public Nullable<bool> is_send_email { get; set; }
        public Nullable<System.DateTime> send_email_date { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> last_regdate { get; set; }
    }
}
