//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_menu_parent
    {
        public int menu_parent_serial_no { get; set; }
        public string menu_parent_name { get; set; }
        public string menu_parent_href { get; set; }
        public Nullable<sbyte> menu_parent_order { get; set; }
    }
}
