//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_news
    {
        public int news_serial_no { get; set; }
        public string news_title { get; set; }
        public string news_body { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public Nullable<int> staff_serial_no { get; set; }
        public Nullable<sbyte> system_category_serial_no { get; set; }
        public Nullable<System.DateTime> news_create_datetime { get; set; }
    }
}
