//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_paypal_record_info
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string card_type { get; set; }
        public string card_number { get; set; }
        public string expiration_date { get; set; }
        public string card_verification_number { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip_code { get; set; }
        public string country { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string amount_unit { get; set; }
        public Nullable<int> order_code { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
