//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_product_sys_detail
    {
        public int sys_tmp_detail { get; set; }
        public string sys_tmp_code { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public string product_name { get; set; }
        public string cate_name { get; set; }
        public Nullable<int> part_quantity { get; set; }
        public Nullable<int> part_max_quantity { get; set; }
        public Nullable<decimal> product_current_price { get; set; }
        public Nullable<decimal> product_current_cost { get; set; }
        public Nullable<int> product_order { get; set; }
        public Nullable<int> system_templete_serial_no { get; set; }
        public Nullable<int> system_product_serial_no { get; set; }
        public Nullable<int> part_group_id { get; set; }
        public Nullable<decimal> save_price { get; set; }
        public Nullable<decimal> old_price { get; set; }
        public Nullable<int> re_sys_tmp_detail { get; set; }
        public Nullable<decimal> product_current_price_rate { get; set; }
        public Nullable<decimal> product_current_sold { get; set; }
        public Nullable<bool> is_lock { get; set; }
        public string ebay_number { get; set; }
    }
}
