//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_facture_state
    {
        public int order_facture_state_serial_no { get; set; }
        public string order_code { get; set; }
        public Nullable<int> facture_state_serial_no { get; set; }
        public Nullable<System.DateTime> order_facture_state_create_date { get; set; }
        public string order_facture_note { get; set; }
    }
}
