//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_pay_status
    {
        public int id { get; set; }
        public string order_pay_status_name { get; set; }
        public string order_pay_status_short_name { get; set; }
        public Nullable<bool> tag { get; set; }
    }
}
