//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_other_inc
    {
        public int id { get; set; }
        public string other_inc_name { get; set; }
        public Nullable<int> other_inc_type { get; set; }
        public Nullable<bool> tag { get; set; }
        public Nullable<int> inc_record { get; set; }
        public Nullable<int> inc_record_valid { get; set; }
        public Nullable<int> inc_record_match { get; set; }
        public Nullable<int> bigger_than_lu { get; set; }
        public Nullable<int> less_than_lu { get; set; }
        public Nullable<int> equal_than_lu { get; set; }
        public Nullable<System.DateTime> last_run_date { get; set; }
    }
}
