//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_part_comment
    {
        public int id { get; set; }
        public Nullable<int> part_sku { get; set; }
        public string part_comment { get; set; }
        public string part_short_comment { get; set; }
    }
}
