//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_part_relation_cpu_fan
    {
        public int id { get; set; }
        public Nullable<int> cpu_sku { get; set; }
        public Nullable<int> fan_sku { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
