//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_part_getin_detail
    {
        public int ID { get; set; }
        public Nullable<int> GetinId { get; set; }
        public Nullable<int> PartSKU { get; set; }
        public Nullable<int> Qty { get; set; }
        public string MFP { get; set; }
        public string PartName { get; set; }
        public string Orders { get; set; }
        public string wholesaler { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
    }
}
