//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pre_index_page_setting
    {
        public int id { get; set; }
        public Nullable<int> sku { get; set; }
        public Nullable<bool> Isys { get; set; }
        public Nullable<int> CateId { get; set; }
        public Nullable<int> priority { get; set; }
        public string title { get; set; }
        public string LCDImage { get; set; }
        public Nullable<int> lcd_p_X { get; set; }
        public Nullable<int> lcd_p_Y { get; set; }
        public Nullable<int> case_p_X { get; set; }
        public Nullable<int> case_p_Y { get; set; }
    }
}
