//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_import_price
    {
        public int id { get; set; }
        public string other_inc_name { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public Nullable<decimal> part_real_cost { get; set; }
        public Nullable<decimal> part_sell { get; set; }
        public Nullable<System.DateTime> part_real_regdate { get; set; }
        public string part_name { get; set; }
        public Nullable<int> part_quantity { get; set; }
        public string vendor_invoice { get; set; }
        public string order_codes { get; set; }
        public Nullable<bool> is_order { get; set; }
        public string note { get; set; }
    }
}
