//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_temp_stock
    {
        public int id { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public Nullable<int> ltd_quantity { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
