//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_rival_store
    {
        public int rival_id { get; set; }
        public Nullable<int> rival_ltd_id { get; set; }
        public string rival_sku { get; set; }
        public string rival_manufacture_code { get; set; }
        public string rival_part_name { get; set; }
        public Nullable<decimal> rival_price { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
