//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_rival_url
    {
        public int id { get; set; }
        public Nullable<int> rival_ltd_id { get; set; }
        public string rival_url { get; set; }
        public Nullable<bool> valid { get; set; }
    }
}
