//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_system_templete_category
    {
        public int system_templete_category_serial_no { get; set; }
        public string system_templete_category_name { get; set; }
        public Nullable<int> system_templete_category_order { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public Nullable<int> old_db_id { get; set; }
        public Nullable<sbyte> is_exist_sub { get; set; }
        public string system_templete_category_name_f { get; set; }
    }
}
