//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_system_templete
    {
        public int system_templete_serial_no { get; set; }
        public string system_templete_name { get; set; }
        public Nullable<float> system_templete_price { get; set; }
        public Nullable<int> system_templete_sale_sum { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> last_regdate { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public Nullable<int> system_templete_category_serial_no { get; set; }
        public Nullable<bool> is_templete { get; set; }
        public Nullable<int> system_templete_order { get; set; }
        public Nullable<sbyte> system_category_serial_no { get; set; }
        public string system_templete_name_f { get; set; }
        public Nullable<sbyte> system_templete_new { get; set; }
        public Nullable<sbyte> system_templete_hot { get; set; }
        public Nullable<int> warranty { get; set; }
        public Nullable<int> system_templete_img_sum { get; set; }
        public string logo_image_filename { get; set; }
        public Nullable<int> system_templete_category_serial_no_old { get; set; }
        public string logo_image_filename_VC { get; set; }
        public string logo_image_filename_sys { get; set; }
        public string keywords { get; set; }
        public Nullable<int> parent_templete_id { get; set; }
        public Nullable<int> grand_templete_id { get; set; }
        public Nullable<decimal> tmp_sell { get; set; }
        public Nullable<decimal> tmp_discount { get; set; }
        public Nullable<int> view_count { get; set; }
        public Nullable<bool> is_modify { get; set; }
    }
}
