//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_state_shipping
    {
        public int state_serial_no { get; set; }
        public string state_name { get; set; }
        public Nullable<float> state_shipping { get; set; }
        public Nullable<int> system_category_serial_no { get; set; }
        public string state_short_name { get; set; }
        public string state_code { get; set; }
        public Nullable<sbyte> gst { get; set; }
        public Nullable<sbyte> pst { get; set; }
        public Nullable<bool> is_paypal { get; set; }
        public Nullable<int> priority { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsOtherCountry { get; set; }
    }
}
