//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_shipping_company
    {
        public int shipping_company_id { get; set; }
        public string shipping_company_name { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> system_category { get; set; }
        public Nullable<bool> is_sales_promotion { get; set; }
        public Nullable<decimal> default_charge { get; set; }
        public Nullable<bool> showit { get; set; }
        public Nullable<bool> is_ebay { get; set; }
    }
}
