//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_split_line
    {
        public int split_line { get; set; }
        public string split_line_name { get; set; }
        public Nullable<int> line_order { get; set; }
        public Nullable<int> menu_child_serial_no { get; set; }
    }
}
