//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_templete_replace_parameter
    {
        public int id { get; set; }
        public string source_string { get; set; }
        public string replace_string { get; set; }
        public string page_name { get; set; }
    }
}
