//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_update_ups
    {
        public int update_ups_id { get; set; }
        public string update_ups_no { get; set; }
        public string update_ups_status { get; set; }
        public string order_code { get; set; }
    }
}
