<html>
<head>
    <title>Category Select</title>
<style>
.validTitle{color: #8B8BD1;}
body { font-size: 8.5pt;}
ul, li { margin-top: 0px; margin-bottom: 10px;}
a { display: block; padding: 2px;}
a:hover { display:block;padding: 2px; background: blue; color: white;}
</style>
</head>

<body>
    <ul><li>Mobile Computers<ul><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '356';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Tablets';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Tablets</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '350';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Laptops';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Laptops</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '355';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Accessories';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Accessories</a>
</li></ul></li><li>Parts & Peripherals<ul><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '378';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Ebay Part';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Ebay Part</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '22';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'CPU';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">CPU</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '91';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Cooling Devices';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Cooling Devices</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '31';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Motherboards';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Motherboards</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '29';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Memory';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Memory</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '456';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Solid State Drives(SSD)';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Solid State Drives(SSD)</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '25';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Hard Drives';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Hard Drives</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '457';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'USB Flash Drives';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">USB Flash Drives</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '40';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Memory Cards';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Memory Cards</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '240';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Optical Drives';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Optical Drives</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '41';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Video Cards';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Video Cards</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '19';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Sound Cards';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Sound Cards</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '259';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Card Reader';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Card Reader</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '33';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Networking';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Networking</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '258';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Cables & Connectors';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Cables & Connectors</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '21';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Computer Cases';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Computer Cases</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '36';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Power Supplies';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Power Supplies</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '26';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Keyboards & Mice';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Keyboards & Mice</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '39';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Speakers';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Speakers</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '28';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Monitors';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Monitors</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '42';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Web Cams';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Web Cams</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '37';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Printers & Scanners';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Printers & Scanners</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '297';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Power Protection';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Power Protection</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '201';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Warranty';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Warranty</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '332';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Services';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Services</a>
</li></ul></li><li>Software<ul><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '216';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Operating Systems';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Operating Systems</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '217';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Microsoft Office';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Microsoft Office</a>
</li><li class='validTitle'><a href='' onclick="parent.document.getElementById('<%= Request.QueryString("id") %>').value = '218';parent.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Anti Virus Software';parent.document.getElementById('<%= Request.QueryString("div_id") %>').style.display='None';return false;">Anti Virus Software</a>
</li></ul></li></ul>
</body>
</html>
