<html>
<head>
    <title>Category Select</title>
</head>
<style>
.validTitle{color: #8B8BD1;}
body { font-size: 8.5pt;}
</style>
<body>
    <ul><li>Notebook Computers<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '86';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Asus Notebooks';window.close();return false;">Asus Notebooks</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '88';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Acer Notebooks';window.close();return false;">Acer Notebooks</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '213';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Fujitsu Notebooks';window.close();return false;">Fujitsu Notebooks</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '90';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'LG Notebooks';window.close();return false;">LG Notebooks</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '306';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Lenovo ThinkPad';window.close();return false;">Lenovo ThinkPad</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '228';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'MSI Notebooks';window.close();return false;">MSI Notebooks</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '227';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'All Notebooks';window.close();return false;">All Notebooks</a></li></li></ul></li><li>Notebook Accessories<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '255';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'for Acer Notebooks';window.close();return false;">for Acer Notebooks</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '256';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'for Asus Notebooks';window.close();return false;">for Asus Notebooks</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '257';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'for LG Notebooks';window.close();return false;">for LG Notebooks</a></li></li></ul></li><li>Parts & Peripherals<ul><li >CPU<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '71';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Intel Processors';window.close();return false;">Intel Processors</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '74';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'AMD Processors';window.close();return false;">AMD Processors</a></li></ul></li><li >Cooling Devices<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '92';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'CPU Fan Cooling';window.close();return false;">CPU Fan Cooling</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '93';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'CPU Water Cooling';window.close();return false;">CPU Water Cooling</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '262';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Video Card Cooling';window.close();return false;">Video Card Cooling</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '264';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Notebook Coolers';window.close();return false;">Notebook Coolers</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '298';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Fans and  Accessories';window.close();return false;">Fans and  Accessories</a></li></ul></li><li >Motherboards<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '333';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Intel Socket 1366';window.close();return false;">Intel Socket 1366</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '60';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Intel Socket 775';window.close();return false;">Intel Socket 775</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '65';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'AMD Socket AM2';window.close();return false;">AMD Socket AM2</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '61';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Intel Xeon Socket 771';window.close();return false;">Intel Xeon Socket 771</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '62';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'AMD Opteron';window.close();return false;">AMD Opteron</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '64';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Other Mother Boards';window.close();return false;">Other Mother Boards</a></li></ul></li><li >Memory<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '97';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'OCZ Memory';window.close();return false;">OCZ Memory</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '95';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Kingston Memory';window.close();return false;">Kingston Memory</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '267';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Crucial Memory';window.close();return false;">Crucial Memory</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '96';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Corsair Memory';window.close();return false;">Corsair Memory</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '94';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Major Brand Memory';window.close();return false;">Major Brand Memory</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '104';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Notebook Memory';window.close();return false;">Notebook Memory</a></li></ul></li><li >Hard Drives<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '100';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'SATA II Hard Drives';window.close();return false;">SATA II Hard Drives</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '103';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Mobile Hard Drives';window.close();return false;">Mobile Hard Drives</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '314';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'WD External (MyBook)';window.close();return false;">WD External (MyBook)</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '300';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Solid-State SATA II';window.close();return false;">Solid-State SATA II</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '99';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'IDE Hard Drives';window.close();return false;">IDE Hard Drives</a></li></ul></li><li >Optical Drives<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '284';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'DVD Writers';window.close();return false;">DVD Writers</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '299';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Blue-Ray';window.close();return false;">Blue-Ray</a></li></ul></li><li >Video Cards<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '234';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'ATI PCI-Express';window.close();return false;">ATI PCI-Express</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '233';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'nVidia PCI-Express';window.close();return false;">nVidia PCI-Express</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '236';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'AGP Cards';window.close();return false;">AGP Cards</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '237';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'PCI Cards';window.close();return false;">PCI Cards</a></li></ul></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '261';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Video Capture / TV Tuners';window.close();return false;">Video Capture / TV Tuners</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '19';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Sound Cards';window.close();return false;">Sound Cards</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '259';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Floppy Drive Card Readers';window.close();return false;">Floppy Drive Card Readers</a></li></li><li >Network Devices<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '124';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Network Adapters';window.close();return false;">Network Adapters</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '146';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Modems';window.close();return false;">Modems</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '125';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Routers / Switches / Hubs';window.close();return false;">Routers / Switches / Hubs</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '126';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Antenna / Bluetooth';window.close();return false;">Antenna / Bluetooth</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '147';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Access Point';window.close();return false;">Access Point</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '145';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'KVM Switches';window.close();return false;">KVM Switches</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '317';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Camera / Phone';window.close();return false;">Camera / Phone</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '318';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Network Storage';window.close();return false;">Network Storage</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '319';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Wireless Media Player';window.close();return false;">Wireless Media Player</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '127';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Networking / Others';window.close();return false;">Networking / Others</a></li></ul></li><li >Computer Cases<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '110';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Standard Cases';window.close();return false;">Standard Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '111';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Antec Cases';window.close();return false;">Antec Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '170';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Apevia Cases';window.close();return false;">Apevia Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '157';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Asus Cases';window.close();return false;">Asus Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '117';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Chenbro Server Cases';window.close();return false;">Chenbro Server Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '116';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Chenmin Cases';window.close();return false;">Chenmin Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '159';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Cooler Master Cases';window.close();return false;">Cooler Master Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '115';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Thermaltake Cases';window.close();return false;">Thermaltake Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '282';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'In-Win Cases';window.close();return false;">In-Win Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '112';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Lian-Li Cases';window.close();return false;">Lian-Li Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '114';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'NZXT Cases';window.close();return false;">NZXT Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '113';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Raidmax Cases';window.close();return false;">Raidmax Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '294';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Sigma Cases';window.close();return false;">Sigma Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '295';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Zalman Cases';window.close();return false;">Zalman Cases</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '328';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Shuttle PC Barebones';window.close();return false;">Shuttle PC Barebones</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '330';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Supermicro Server Cases';window.close();return false;">Supermicro Server Cases</a></li></ul></li><li >Power Supplies<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '315';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'ALL';window.close();return false;">ALL</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '162';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Generic';window.close();return false;">Generic</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '164';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'OCZ';window.close();return false;">OCZ</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '166';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Thermaltake';window.close();return false;">Thermaltake</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '269';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'BFG';window.close();return false;">BFG</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '163';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Antec';window.close();return false;">Antec</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '296';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'PC Power & Cooling';window.close();return false;">PC Power & Cooling</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '165';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Seasonic';window.close();return false;">Seasonic</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '271';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Cooler Master';window.close();return false;">Cooler Master</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '272';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Enermax';window.close();return false;">Enermax</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '273';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Apevia';window.close();return false;">Apevia</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '274';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Zalman';window.close();return false;">Zalman</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '331';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Chenbro';window.close();return false;">Chenbro</a></li></ul></li><li >Neon Light Products<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '131';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Neon Light';window.close();return false;">Neon Light</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '133';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Bubble Neon Light';window.close();return false;">Bubble Neon Light</a></li></ul></li><li >Keyboards & Mice<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '324';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'ALL';window.close();return false;">ALL</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '121';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Keyboards';window.close();return false;">Keyboards</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '122';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Mice';window.close();return false;">Mice</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '123';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Keyboard & Mouse Combo';window.close();return false;">Keyboard & Mouse Combo</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '148';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Accessories';window.close();return false;">Accessories</a></li></ul></li><li >Speakers<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '171';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Speaker Systems';window.close();return false;">Speaker Systems</a></li></ul></li><li >LCD Monitors<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '325';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Featured';window.close();return false;">Featured</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '327';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'All';window.close();return false;">All</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '102';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = '17 Inch LCD';window.close();return false;">17 Inch LCD</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '149';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = '19 Inch LCD';window.close();return false;">19 Inch LCD</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '150';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = '20 Inch LCD';window.close();return false;">20 Inch LCD</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '276';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = '22 Inch LCD';window.close();return false;">22 Inch LCD</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '277';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = '24 Inch LCD';window.close();return false;">24 Inch LCD</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '278';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = '32 Inch-70 Inch LCD/TV';window.close();return false;">32 Inch-70 Inch LCD/TV</a></li></ul></li><li >CD Media<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '44';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'CDs';window.close();return false;">CDs</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '45';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'DVDs';window.close();return false;">DVDs</a></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '46';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'DVD Boxes';window.close();return false;">DVD Boxes</a></li></ul></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '42';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Web Cams';window.close();return false;">Web Cams</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '24';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Drive Enclosures';window.close();return false;">Drive Enclosures</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '37';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Printers';window.close();return false;">Printers</a></li></li><li >Mini PC Barebone Kits<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '152';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Shuttle Mini PC';window.close();return false;">Shuttle Mini PC</a></li></ul></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '297';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Power Protection';window.close();return false;">Power Protection</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '304';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'GPS Device';window.close();return false;">GPS Device</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '201';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Warranty';window.close();return false;">Warranty</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '332';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Services';window.close();return false;">Services</a></li></li></ul></li><li>Software<ul><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '216';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Operating Systems';window.close();return false;">Operating Systems</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '217';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Microsoft Office';window.close();return false;">Microsoft Office</a></li></li><li class='validTitle'><a href='' onclick="opener.document.getElementById('<%= Request.QueryString("id") %>').value = '218';
            opener.document.getElementById('<%= Request.QueryString("textid") %>').value = 'Anti Virus Software';window.close();return false;">Anti Virus Software</a></li></li></ul></li></ul>
</body>
</html>
