//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TransitShipment
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class nicklu2Entities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“nicklu2Entities”部分中的连接字符串初始化新 nicklu2Entities 对象。
        /// </summary>
        public nicklu2Entities() : base("name=nicklu2Entities", "nicklu2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 nicklu2Entities 对象。
        /// </summary>
        public nicklu2Entities(string connectionString) : base(connectionString, "nicklu2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 nicklu2Entities 对象。
        /// </summary>
        public nicklu2Entities(EntityConnection connection) : base(connection, "nicklu2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tb_timer> tb_timer
        {
            get
            {
                if ((_tb_timer == null))
                {
                    _tb_timer = base.CreateObjectSet<tb_timer>("tb_timer");
                }
                return _tb_timer;
            }
        }
        private ObjectSet<tb_timer> _tb_timer;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 tb_timer EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotb_timer(tb_timer tb_timer)
        {
            base.AddObject("tb_timer", tb_timer);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="nicklu2Model", Name="tb_timer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_timer : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tb_timer 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="cmdContent">CmdContent 属性的初始值。</param>
        /// <param name="cmd">Cmd 属性的初始值。</param>
        /// <param name="regdate">regdate 属性的初始值。</param>
        /// <param name="status">Status 属性的初始值。</param>
        public static tb_timer Createtb_timer(global::System.Int32 id, global::System.String cmdContent, global::System.String cmd, global::System.DateTime regdate, global::System.Int32 status)
        {
            tb_timer tb_timer = new tb_timer();
            tb_timer.ID = id;
            tb_timer.CmdContent = cmdContent;
            tb_timer.Cmd = cmd;
            tb_timer.regdate = regdate;
            tb_timer.Status = status;
            return tb_timer;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CmdContent
        {
            get
            {
                return _CmdContent;
            }
            set
            {
                OnCmdContentChanging(value);
                ReportPropertyChanging("CmdContent");
                _CmdContent = StructuralObject.SetValidValue(value, false, "CmdContent");
                ReportPropertyChanged("CmdContent");
                OnCmdContentChanged();
            }
        }
        private global::System.String _CmdContent;
        partial void OnCmdContentChanging(global::System.String value);
        partial void OnCmdContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cmd
        {
            get
            {
                return _Cmd;
            }
            set
            {
                OnCmdChanging(value);
                ReportPropertyChanging("Cmd");
                _Cmd = StructuralObject.SetValidValue(value, false, "Cmd");
                ReportPropertyChanged("Cmd");
                OnCmdChanged();
            }
        }
        private global::System.String _Cmd;
        partial void OnCmdChanging(global::System.String value);
        partial void OnCmdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime regdate
        {
            get
            {
                return _regdate;
            }
            set
            {
                OnregdateChanging(value);
                ReportPropertyChanging("regdate");
                _regdate = StructuralObject.SetValidValue(value, "regdate");
                ReportPropertyChanged("regdate");
                OnregdateChanged();
            }
        }
        private global::System.DateTime _regdate;
        partial void OnregdateChanging(global::System.DateTime value);
        partial void OnregdateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();

        #endregion

    }

    #endregion

}
