//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunStore.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qstoreEntities : DbContext
    {
        public qstoreEntities()
            : base("name=qstoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_yun_fileinfo_sale_child> tb_yun_fileinfo_sale_child { get; set; }
        public virtual DbSet<tb_yun_fileinfo_sale_main> tb_yun_fileinfo_sale_main { get; set; }
        public virtual DbSet<tb_yun_fileinfo_stock_child> tb_yun_fileinfo_stock_child { get; set; }
        public virtual DbSet<tb_yun_fileinfo_stock_main> tb_yun_fileinfo_stock_main { get; set; }
        public virtual DbSet<tb_yun_fileinfo_company_stock> tb_yun_fileinfo_company_stock { get; set; }
        public virtual DbSet<tb_yun_fileinfo_company_stock_record> tb_yun_fileinfo_company_stock_record { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
        public virtual DbSet<tb_profit> tb_profit { get; set; }
    }
}
