//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_serial
    {
        public string Gid { get; set; }
        public string ProdCode { get; set; }
        public string ProdSerialNo { get; set; }
        public int WarehouseId { get; set; }
        public string WarehouseChangeDate { get; set; }
        public int StockType { get; set; }
        public string InRegdate { get; set; }
        public string OutRegdate { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
    }
}
