//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_profit
    {
        public System.Guid Gid { get; set; }
        public string Regdate { get; set; }
        public string StaffName { get; set; }
        public System.Guid StaffGid { get; set; }
        public string ProfitDate { get; set; }
        public decimal Profit { get; set; }
        public decimal Sale { get; set; }
        public decimal RenLiChengBen1 { get; set; }
        public decimal GuDingChengBen1 { get; set; }
        public decimal YingXiaoChengBen1 { get; set; }
        public decimal ChanPinChengBen1 { get; set; }
        public decimal YunCangChengBen1 { get; set; }
        public decimal GongZi { get; set; }
        public decimal SiJiFeiYong { get; set; }
        public decimal DaiYunYingFeiYong { get; set; }
        public decimal BanGongYongPin { get; set; }
        public decimal ShuiDianFeiYong { get; set; }
        public decimal FangWuZuJin { get; set; }
        public decimal ShuiWuFeiYong { get; set; }
        public decimal QiTaZaFei { get; set; }
        public decimal DaiFuFeiYong { get; set; }
        public decimal CaiWuJiZhangFei { get; set; }
        public decimal ZhiTongChe { get; set; }
        public decimal ZuanZhanFei { get; set; }
        public decimal QiTaFeiYong { get; set; }
        public decimal CDianZhiTongChe { get; set; }
        public decimal JinHuoChengBen { get; set; }
        public decimal ShangNiChengBen { get; set; }
        public decimal FeiDiLaChengBen { get; set; }
        public decimal XinRuiChengBen { get; set; }
        public decimal HongWeiWuLiuChengBen { get; set; }
        public decimal EKOFaHuoShangPinChengBen { get; set; }
        public decimal NutFangDiuQi { get; set; }
        public decimal CangChuFeiYuFaHuoFeiYong { get; set; }
        public decimal HaoCaiFei { get; set; }
        public decimal DingZhiXiangFeiYong { get; set; }
        public decimal ChaoJiTuiJian { get; set; }
        public decimal MaoLi { get; set; }
        public decimal SheBaoGongJiJin { get; set; }
    }
}
