//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public string gid { get; set; }
        public string user_name { get; set; }
        public string user_pwd { get; set; }
        public string regdate { get; set; }
    }
}
