//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string user_pwd { get; set; }
        public Nullable<bool> showit { get; set; }
        public string user_code { get; set; }
        public Nullable<bool> is_admin { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string comment { get; set; }
        public string section { get; set; }
        public System.DateTime regdate { get; set; }
        public System.Guid Gid { get; set; }
    }
}
