//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_yun_fileinfo_stock_main
    {
        public string Gid { get; set; }
        public string Regdate { get; set; }
        public string StaffName { get; set; }
        public string StaffId { get; set; }
        public string FileName { get; set; }
        public string FileMD5 { get; set; }
        public int AllProdQty { get; set; }
        public int AllProdStock { get; set; }
        public decimal AllProdTotal { get; set; }
    }
}
