//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_yun_fileinfo_company_stock_record
    {
        public System.Guid Gid { get; set; }
        public string ProdCode { get; set; }
        public string ProdName { get; set; }
        public decimal Price { get; set; }
        public decimal Cost { get; set; }
        public string Regdate { get; set; }
        public System.Guid StaffGid { get; set; }
        public string StaffName { get; set; }
        public int Qty { get; set; }
        public string Remark { get; set; }
        public string InOut { get; set; }
    }
}
