//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_yun_fileInfo_stock_child
    {
        public string Gid { get; set; }
        public string Regdate { get; set; }
        public string ParentId { get; set; }
        public string ProdCode { get; set; }
        public string SpecCode { get; set; }
        public string ProdName { get; set; }
        public string ProdSpec { get; set; }
        public string ProdSN { get; set; }
        public int QtyAll { get; set; }
        public int QtyStock { get; set; }
        public int QtyOn { get; set; }
        public int QtyUsed { get; set; }
        public decimal Total { get; set; }
        public int Qty30DaySale { get; set; }
        public int QtyWarn { get; set; }
    }
}
