//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YunStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_yun_fileinfo_stock_child
    {
        public System.Guid Gid { get; set; }
        public string Regdate { get; set; }
        public System.Guid ParentId { get; set; }
        public string ProdCode { get; set; }
        public string SpecCode { get; set; }
        public string ProdName { get; set; }
        public string ProdSpec { get; set; }
        public string ProdSN { get; set; }
        public int QtyAll { get; set; }
        public int QtyStock { get; set; }
        public int QtyOn { get; set; }
        public int QtyUsed { get; set; }
        public decimal Total { get; set; }
        public int Qty30DaySale { get; set; }
        public int QtyWarn { get; set; }
    }
}
