//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_balance_cash_record
    {
        public int Id { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreatorName { get; set; }
        public System.DateTime PayDate { get; set; }
        public decimal PayCash { get; set; }
        public string PayNote { get; set; }
        public decimal PreBalance { get; set; }
        public int CreatorId { get; set; }
        public decimal IncomeCash { get; set; }
        public decimal AfterBalance { get; set; }
        public bool IsExclude { get; set; }
        public int PayType { get; set; }
    }
}
