//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_proxy
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> SaleQuantity { get; set; }
        public Nullable<decimal> SaleTotal { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
        public string Note { get; set; }
    }
}
