//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product
    {
        public int id { get; set; }
        public string p_code { get; set; }
        public string num_iid { get; set; }
        public string p_name { get; set; }
        public Nullable<int> p_cate_id { get; set; }
        public Nullable<decimal> p_price { get; set; }
        public Nullable<decimal> p_cost { get; set; }
        public Nullable<int> p_quantity { get; set; }
        public string p_taobao_url { get; set; }
        public Nullable<bool> showit { get; set; }
        public string WholesalerCode { get; set; }
        public string WholesalerUrl { get; set; }
        public string brand { get; set; }
        public Nullable<int> WarnQty { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public string yun_code { get; set; }
    }
}
