//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_return_history
    {
        public int id { get; set; }
        public string SerialNo { get; set; }
        public string out_invoice_id { get; set; }
        public string out_invoice_code { get; set; }
        public Nullable<int> p_id { get; set; }
        public string p_code { get; set; }
        public Nullable<System.DateTime> return_regdate { get; set; }
        public string comment { get; set; }
        public string staff { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
