//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_serial_no_and_p_code
    {
        public int id { get; set; }
        public string SerialNO { get; set; }
        public Nullable<int> p_id { get; set; }
        public string p_code { get; set; }
        public Nullable<decimal> in_cost { get; set; }
        public Nullable<System.DateTime> in_regdate { get; set; }
        public Nullable<System.DateTime> out_regdate { get; set; }
        public Nullable<bool> is_order_code { get; set; }
        public Nullable<bool> is_return { get; set; }
        public Nullable<System.DateTime> return_regdate { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsReturnWholesaler { get; set; }
        public Nullable<System.DateTime> IsReturnWholesaler_regdate { get; set; }
        public string in_invoice_code { get; set; }
        public Nullable<int> curr_warehouse_id { get; set; }
        public Nullable<System.DateTime> curr_warehouse_date { get; set; }
        public Nullable<bool> IsFree { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
