//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sn_change_record
    {
        public int ID { get; set; }
        public string SerialNo { get; set; }
        public string OldProductCode { get; set; }
        public string NewProductCode { get; set; }
        public string Staff { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
    }
}
