//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_serial_no
    {
        public int id { get; set; }
        public string SerialNo { get; set; }
        public Nullable<bool> is_print { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
