//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string user_pwd { get; set; }
        public Nullable<bool> showit { get; set; }
        public string user_code { get; set; }
        public Nullable<bool> is_admin { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string comment { get; set; }
        public string section { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
