//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_yun_stock_async
    {
        public int Id { get; set; }
        public System.DateTime Regdate { get; set; }
        public int StaffId { get; set; }
        public string StaffName { get; set; }
        public string yun_code { get; set; }
        public int yun_qty { get; set; }
        public string p_code { get; set; }
        public int p_qty { get; set; }
        public int p_id { get; set; }
    }
}
