//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbtoken
    {
        public System.Guid Gid { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public bool Showit { get; set; }
    }
}
