//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_advertise
    {
        public int advertise_serial_no { get; set; }
        public string comment { get; set; }
        public string image_file_name { get; set; }
        public string advertise_link_url { get; set; }
        public Nullable<sbyte> advertise_type { get; set; }
    }
}
