//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_customer_bank
    {
        public int customer_bank_serial_no { get; set; }
        public string customer_bank_type { get; set; }
        public string customer_bank_code { get; set; }
        public Nullable<System.DateTime> customer_bank_exp_date { get; set; }
        public string customer_bank_security_code { get; set; }
        public string customer_bank_phone { get; set; }
    }
}
