//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_selling_timeleft_tmp
    {
        public int id { get; set; }
        public string TimeLeft { get; set; }
        public string BuyItNowPrice { get; set; }
        public string regdate { get; set; }
        public string ItemID { get; set; }
    }
}
