//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_promotional_sale_id
    {
        public int Id { get; set; }
        public decimal price { get; set; }
        public System.DateTime beginDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string PromotionalSaleID { get; set; }
        public string title { get; set; }
        public bool auto { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
