//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_templete_sub_summary
    {
        public int id { get; set; }
        public Nullable<int> templete_id { get; set; }
        public string brand { get; set; }
        public string comment { get; set; }
        public string summary { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
