//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_store_detail
    {
        public int id { get; set; }
        public Nullable<int> part_group_id { get; set; }
        public Nullable<int> lu_sku { get; set; }
        public string part_comment { get; set; }
        public string part_name { get; set; }
        public Nullable<int> ebay_store_id { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> last_regdate { get; set; }
    }
}
