//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_turbolist
    {
        public int id { get; set; }
        public string sold_status { get; set; }
        public string item_id { get; set; }
        public string item_title { get; set; }
        public string format_type { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public Nullable<decimal> start_price { get; set; }
        public string price_unit { get; set; }
        public string custom_label { get; set; }
        public string shipping_type { get; set; }
        public string shipping_service { get; set; }
        public Nullable<decimal> shipping_cost { get; set; }
        public string shipping_cost_unit { get; set; }
        public Nullable<decimal> handling_cost { get; set; }
        public string handling_cost_unit { get; set; }
        public string weight_lbs { get; set; }
        public string weight_oz { get; set; }
        public Nullable<int> available_quantity { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
