//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_shipping_settings
    {
        public int ID { get; set; }
        public Nullable<decimal> shippingFee { get; set; }
        public string shippingCompany { get; set; }
        public Nullable<bool> IsFree { get; set; }
        public string CategoryID { get; set; }
        public string ShortCategoryName { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
