//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_modify_price_history
    {
        public int id { get; set; }
        public Nullable<int> lu_part_id { get; set; }
        public Nullable<decimal> lu_price { get; set; }
        public Nullable<decimal> lu_price_discount { get; set; }
        public Nullable<decimal> lu_rebate_price { get; set; }
        public Nullable<decimal> lu_new_price { get; set; }
        public Nullable<decimal> etc_price { get; set; }
        public Nullable<System.DateTime> load_date { get; set; }
        public Nullable<int> etc_part_id { get; set; }
    }
}
