//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_news_letter
    {
        public int news_letter_serial_no { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<sbyte> tag { get; set; }
    }
}
