//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_product_temp
    {
        public int serial_no { get; set; }
        public Nullable<int> order_serial_no { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<int> order_product_sum { get; set; }
        public Nullable<float> order_product_price { get; set; }
        public Nullable<int> customer_serial_no { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public string sku { get; set; }
    }
}
