//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_other_inc_valid_lu_sku
    {
        public int id { get; set; }
        public Nullable<int> lu_sku { get; set; }
        public string manufacturer_part_number { get; set; }
        public Nullable<bool> is_valid { get; set; }
        public Nullable<bool> is_ncix_remain { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<int> ltd_stock { get; set; }
        public Nullable<int> menu_child_serial_no { get; set; }
        public string brand { get; set; }
        public Nullable<decimal> adjustment { get; set; }
        public string prodType { get; set; }
    }
}
