//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_invoice_void
    {
        public int invoice_id { get; set; }
        public Nullable<int> invoice_code { get; set; }
        public Nullable<bool> is_lock { get; set; }
        public Nullable<int> order_code { get; set; }
    }
}
