//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_assigned_to
    {
        public int assigned_to_id { get; set; }
        public string assigned_to_staff_name { get; set; }
        public Nullable<int> assigned_to_staff_id { get; set; }
        public string assigned_to_comment { get; set; }
        public Nullable<int> edit_staff_id { get; set; }
        public string eidt_staff_name { get; set; }
        public Nullable<int> order_code { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
