//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_other_inc_shopbot
    {
        public int id { get; set; }
        public Nullable<int> lu_sku { get; set; }
        public string other_inc_name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
