//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_other_inc_bind_price_tmp_history
    {
        public int id { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<int> category_id { get; set; }
        public string other_inc_sku { get; set; }
        public Nullable<decimal> other_inc_price { get; set; }
        public Nullable<int> other_inc_store_sum { get; set; }
        public Nullable<int> other_inc_id { get; set; }
        public Nullable<decimal> product_current_price { get; set; }
        public Nullable<decimal> product_current_price_tmp { get; set; }
        public Nullable<decimal> product_current_cost { get; set; }
        public string mark { get; set; }
        public Nullable<int> bind_type { get; set; }
    }
}
