//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_price_tmp
    {
        public int id { get; set; }
        public Nullable<decimal> curr_change_cost { get; set; }
        public Nullable<decimal> curr_change_price { get; set; }
        public string curr_change_ltd { get; set; }
        public Nullable<int> curr_change_quantity { get; set; }
        public string curr_change_regdate { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public Nullable<bool> is_auto_change { get; set; }
    }
}
