//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_out
    {
        public int product_out_serial_no { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<System.DateTime> product_out_date { get; set; }
        public Nullable<int> product_out_sale_staff { get; set; }
        public Nullable<int> product_out_staff { get; set; }
        public Nullable<System.DateTime> product_out_end_date { get; set; }
        public Nullable<decimal> product_detail_out_price { get; set; }
        public Nullable<int> product_out_client { get; set; }
        public string product_out_receipt { get; set; }
        public Nullable<int> system_category_serial_no { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public string product_sn { get; set; }
    }
}
