//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pay_method_new
    {
        public int pay_method_serial_no { get; set; }
        public string pay_method_name { get; set; }
        public string pay_check_path_new { get; set; }
        public string pay_check_path { get; set; }
        public Nullable<int> taxis { get; set; }
        public string pay_method_short_name { get; set; }
        public Nullable<bool> tag { get; set; }
        public Nullable<int> priority { get; set; }
        public string AD { get; set; }
        public Nullable<bool> is_card { get; set; }
        public string supper_country { get; set; }
    }
}
