//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_titles
    {
        public int serial_no { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public string title_short { get; set; }
        public string title_mid { get; set; }
        public string title_long { get; set; }
        public string language { get; set; }
    }
}
