//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_part_app_page_url
    {
        public int ID { get; set; }
        public int SKU { get; set; }
        public string PageUrl { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
