//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_part_group
    {
        public int part_group_id { get; set; }
        public Nullable<int> product_category { get; set; }
        public string part_group_name { get; set; }
        public Nullable<bool> showit { get; set; }
        public string part_group_comment { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<bool> none_option { get; set; }
        public Nullable<bool> is_ebay { get; set; }
    }
}
