//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_category_keyword
    {
        public int id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string keyword { get; set; }
        public Nullable<bool> showit { get; set; }
        public Nullable<bool> is_ebay { get; set; }
        public Nullable<bool> is_price { get; set; }
        public bool IsShowOnWebPage { get; set; }
        public Nullable<int> priority { get; set; }
    }
}
