//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_part_relation_motherboard_video_audio_port
    {
        public int id { get; set; }
        public Nullable<int> mb_sku { get; set; }
        public Nullable<int> video_sku { get; set; }
        public Nullable<int> audio_sku { get; set; }
        public Nullable<int> port_sku { get; set; }
        public Nullable<int> network_sku { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
