//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_part_cpu_and_comment
    {
        public int ID { get; set; }
        public int luc_sku { get; set; }
        public int commentID { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
