//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_virtual
    {
        public int id { get; set; }
        public Nullable<int> lu_sku { get; set; }
        public Nullable<int> menu_child_serial_no { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<bool> showit { get; set; }
    }
}
