//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_in
    {
        public int product_in_serial_no { get; set; }
        public Nullable<float> product_in_cost { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<System.DateTime> product_in_date { get; set; }
        public string purchase_serial_no { get; set; }
        public Nullable<int> product_in_staff { get; set; }
        public Nullable<float> product_in_price { get; set; }
        public Nullable<int> product_in_sum { get; set; }
        public Nullable<System.DateTime> product_in_end_date { get; set; }
        public Nullable<float> tag { get; set; }
        public string product_sns { get; set; }
        public Nullable<int> system_category_serial_no { get; set; }
        public Nullable<int> vendor_serial_no { get; set; }
    }
}
