//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_size
    {
        public int product_size_id { get; set; }
        public string product_size_name { get; set; }
        public Nullable<decimal> begin_price { get; set; }
        public Nullable<decimal> end_price { get; set; }
        public Nullable<int> product_type { get; set; }
    }
}
