//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_supercom_notebook
    {
        public int id { get; set; }
        public string mfp { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string name { get; set; }
        public string brand { get; set; }
        public string category { get; set; }
        public string supercom_SKU { get; set; }
        public Nullable<int> LUC_SKU { get; set; }
        public Nullable<decimal> supercom_cost { get; set; }
        public Nullable<decimal> DanDh_cost { get; set; }
        public Nullable<decimal> synnex_cost { get; set; }
        public string UPC { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
