//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_staff
    {
        public int staff_serial_no { get; set; }
        public string staff_login_name { get; set; }
        public string staff_email { get; set; }
        public string staff_phone { get; set; }
        public Nullable<bool> tag { get; set; }
        public string staff_password { get; set; }
        public string staff_realname { get; set; }
        public Nullable<System.DateTime> staff_last_login_date { get; set; }
        public string staff_system_category { get; set; }
        public Nullable<bool> staff_type { get; set; }
    }
}
