//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_system_product
    {
        public int system_product_serial_no { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<int> system_templete_serial_no { get; set; }
        public Nullable<int> product_order { get; set; }
        public Nullable<sbyte> showit { get; set; }
        public Nullable<int> part_quantity { get; set; }
        public Nullable<int> part_max_quantity { get; set; }
        public Nullable<int> part_group_id { get; set; }
        public Nullable<bool> is_exce_add { get; set; }
    }
}
