//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_update_relation
    {
        public int update_relation_id { get; set; }
        public string update_relation_table_a { get; set; }
        public string update_relation_table_a_fields { get; set; }
        public string update_relation_table_b { get; set; }
        public string update_relation_table_b_fields { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public string update_relation_table_a_fields_comment { get; set; }
        public string update_relation_table_b_fields_comment { get; set; }
    }
}
