//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DownloadEBayOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_vendor
    {
        public string company_name { get; set; }
        public string customer { get; set; }
        public Nullable<int> account_number { get; set; }
        public string sales_person { get; set; }
        public string telephone1 { get; set; }
        public string telephone2 { get; set; }
        public string fax { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string cite_state_zip { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string rma_telphone { get; set; }
        public string rma_person { get; set; }
        public string note { get; set; }
        public string vendor_category { get; set; }
        public int vendor_serial_no { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public string user_name { get; set; }
        public string pass_word { get; set; }
        public string msn { get; set; }
        public string icq { get; set; }
        public Nullable<int> system_category_serial_no { get; set; }
    }
}
