//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKWStore.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_check_store
    {
        public int id { get; set; }
        public System.DateTime check_regdate { get; set; }
        public string comment { get; set; }
        public string staff { get; set; }
        public int valid_quantity { get; set; }
        public int err_quantity { get; set; }
        public int CheckStatus { get; set; }
        public int AutoRunStatus { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
