//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKWStore.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_in_invoice
    {
        public int id { get; set; }
        public Nullable<System.DateTime> input_regdate { get; set; }
        public string invoice_code { get; set; }
        public string Supplier { get; set; }
        public string staff { get; set; }
        public string summary { get; set; }
        public string note { get; set; }
        public string pay_method { get; set; }
        public Nullable<decimal> pay_total { get; set; }
        public Nullable<int> curr_warehouse_id { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
