//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKWStore.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_out_invoice_product
    {
        public int id { get; set; }
        public Nullable<int> out_invoice_id { get; set; }
        public string out_invoice_code { get; set; }
        public int p_id { get; set; }
        public string SerialNO { get; set; }
        public Nullable<bool> is_return { get; set; }
        public System.DateTime regdate { get; set; }
        public bool IsFree { get; set; }
    }
}
