//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKWStore.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order
    {
        public int Id { get; set; }
        public System.DateTime Regdate { get; set; }
        public string Staff { get; set; }
        public int Flag { get; set; }
        public string TraceNo { get; set; }
        public string BrandNo { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Source { get; set; }
        public string OrderType { get; set; }
        public string CustomerName { get; set; }
        public string ProdName { get; set; }
        public decimal Total { get; set; }
        public string InOut { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<decimal> ServiceFee { get; set; }
        public Nullable<decimal> ReturnFee { get; set; }
        public string Note { get; set; }
        public string MoneyStatus { get; set; }
    }
}
