//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKWStore.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_return_wholesaler_detail
    {
        public int ID { get; set; }
        public string ReturnCode { get; set; }
        public string SN { get; set; }
        public string p_name { get; set; }
        public string p_code { get; set; }
        public string in_invoice_code { get; set; }
        public Nullable<System.DateTime> InStoreDate { get; set; }
        public Nullable<bool> IsReturnWholesaler { get; set; }
        public string Brand { get; set; }
        public Nullable<System.DateTime> ReturnRegdate { get; set; }
    }
}
