//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKWStore.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_yun_stock_async_code
    {
        public int Id { get; set; }
        public System.DateTime regdate { get; set; }
        public int staff_id { get; set; }
        public string staff_name { get; set; }
        public int yun_stock_async_id { get; set; }
        public int p_id { get; set; }
        public string p_code { get; set; }
        public string serial_no { get; set; }
        public string cmd { get; set; }
    }
}
