//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKWStore.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_yun_stock_child
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string ProdCode { get; set; }
        public string ProdName { get; set; }
        public string ProdSN { get; set; }
        public string ProdStandard { get; set; }
        public int ProdQtyTotal { get; set; }
        public int ProdQtyUsedOrder { get; set; }
        public int ProdQtyAvailability { get; set; }
        public int ProdQtyWarn { get; set; }
        public System.DateTime Regdate { get; set; }
    }
}
