//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKWStore.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_yun_stock_main
    {
        public int Id { get; set; }
        public System.DateTime regdate { get; set; }
        public string StaffName { get; set; }
        public int StaffId { get; set; }
        public string FileName { get; set; }
    }
}
