//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_advertise
    {
        public int advertise_serial_no { get; set; }
        public string comment { get; set; }
        public string image_file_name { get; set; }
        public string advertise_link_url { get; set; }
        public Nullable<sbyte> advertise_type { get; set; }
    }
}
