//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_cart_temp
    {
        public int cart_temp_serial_no { get; set; }
        public Nullable<int> cart_temp_code { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<int> menu_child_serial_no { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public string ip { get; set; }
        public string customer { get; set; }
        public Nullable<int> cart_temp_Quantity { get; set; }
        public Nullable<int> customer_serial_no { get; set; }
        public Nullable<int> shipping_company { get; set; }
        public Nullable<int> state_shipping { get; set; }
        public Nullable<decimal> shipping_charge { get; set; }
        public Nullable<decimal> sale_tax { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<sbyte> is_noebook { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> old_price { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> pay_method { get; set; }
        public Nullable<System.DateTime> pick_datetime_1 { get; set; }
        public Nullable<System.DateTime> pick_datetime_2 { get; set; }
        public Nullable<decimal> save_price { get; set; }
        public Nullable<decimal> price_rate { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string shipping_state_code { get; set; }
        public string shipping_country_code { get; set; }
        public string prodType { get; set; }
        public string price_unit { get; set; }
        public Nullable<int> current_system { get; set; }
    }
}
