//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_customer_2008
    {
        public string zip_code { get; set; }
        public int customer_serial_no { get; set; }
        public string customer_login_name { get; set; }
        public string customer_business_telephone { get; set; }
        public string phone_d { get; set; }
        public string phone_n { get; set; }
        public string customer_address1 { get; set; }
        public string customer_city { get; set; }
        public string customer_country { get; set; }
        public string customer_email1 { get; set; }
        public string customer_email2 { get; set; }
        public string customer_credit_card { get; set; }
        public string customer_expiry { get; set; }
        public string customer_company { get; set; }
        public string customer_fax { get; set; }
        public string customer_note { get; set; }
        public string customer_password { get; set; }
        public Nullable<int> state_serial_no { get; set; }
        public Nullable<int> tag { get; set; }
        public Nullable<int> system_category_serial_no { get; set; }
        public string customer_first_name { get; set; }
        public string customer_last_name { get; set; }
        public string customer_rumor { get; set; }
        public string customer_card_type { get; set; }
        public string customer_card_phone { get; set; }
        public string EBay_ID { get; set; }
        public int news_latter_subscribe { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public string customer_card_issuer { get; set; }
        public string customer_card_billing_shipping_address { get; set; }
        public string customer_card_city { get; set; }
        public Nullable<int> customer_card_state { get; set; }
        public string customer_card_zip_code { get; set; }
        public Nullable<int> pay_method { get; set; }
        public string customer_shipping_city { get; set; }
        public Nullable<int> customer_shipping_state { get; set; }
        public string customer_shipping_address { get; set; }
        public Nullable<int> customer_card_country { get; set; }
        public string my_purchase_order { get; set; }
        public string customer_shipping_first_name { get; set; }
        public string customer_shipping_last_name { get; set; }
        public Nullable<int> customer_shipping_country { get; set; }
        public string customer_shipping_zip_code { get; set; }
        public string tax_execmtion { get; set; }
        public string busniess_website { get; set; }
        public string phone_c { get; set; }
        public string customer_comment_note { get; set; }
        public Nullable<bool> is_old { get; set; }
        public string card_verification_number { get; set; }
    }
}
