//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_customer_bank
    {
        public int customer_bank_serial_no { get; set; }
        public string customer_bank_type { get; set; }
        public string customer_bank_code { get; set; }
        public Nullable<System.DateTime> customer_bank_exp_date { get; set; }
        public string customer_bank_security_code { get; set; }
        public string customer_bank_phone { get; set; }
    }
}
