//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_customer_helper
    {
        public int cumtomer_helper_serial_no { get; set; }
        public string customer_helper_receiver_name { get; set; }
        public string customer_helper_telephone { get; set; }
        public string customer_helper_shipping_address { get; set; }
        public string customer_helper_city { get; set; }
        public Nullable<int> state_serial_no { get; set; }
        public string customer_helper_country { get; set; }
        public string customer_helper_zip_code { get; set; }
        public string customer_helper_tax_status { get; set; }
        public Nullable<int> customer_serial_no { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
