//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_customer_helper
    {
        public int cumtomer_helper_serial_no { get; set; }
        public string customer_helper_receiver_name { get; set; }
        public string customer_helper_telephone { get; set; }
        public string customer_helper_shipping_address { get; set; }
        public string customer_helper_city { get; set; }
        public Nullable<int> state_serial_no { get; set; }
        public string customer_helper_country { get; set; }
        public string customer_helper_zip_code { get; set; }
        public string customer_helper_tax_status { get; set; }
        public Nullable<int> customer_serial_no { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
