//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_currency_convert_cn
    {
        public int id { get; set; }
        public Nullable<decimal> currency_cn { get; set; }
        public Nullable<decimal> currency_ca { get; set; }
        public Nullable<bool> is_current { get; set; }
        public Nullable<bool> is_auto { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<bool> is_modify { get; set; }
    }
}
