//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_discount_end_date
    {
        public int id { get; set; }
        public string CompanyName { get; set; }
        public string Discount { get; set; }
        public string DiscountEndDate { get; set; }
        public string MFP { get; set; }
        public string PartName { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
