//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_ebay_code_and_luc_sku
    {
        public int id { get; set; }
        public Nullable<int> SKU { get; set; }
        public Nullable<bool> is_sys { get; set; }
        public string ebay_code { get; set; }
        public Nullable<decimal> BuyItNowPrice { get; set; }
        public Nullable<bool> is_online { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
