//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_etc_items
    {
        public int ID { get; set; }
        public string ItemID { get; set; }
        public string ItemTitle { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<int> LUC_eBay_Sys_Sku { get; set; }
        public string ItemType { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
    }
}
