//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_templete
    {
        public int id { get; set; }
        public string templete_comment { get; set; }
        public string templete_content { get; set; }
        public string templete_content2 { get; set; }
        public string templete_info { get; set; }
        public string templete_top { get; set; }
        public Nullable<bool> templete_type { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> last_regdate { get; set; }
        public string comment { get; set; }
        public string templete_summ_1 { get; set; }
        public string templete_summ_2 { get; set; }
    }
}
