//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_store_page
    {
        public int id { get; set; }
        public Nullable<int> ebay_templete_id { get; set; }
        public string ebay_templete_comment { get; set; }
        public string ebay_templete_content { get; set; }
        public string ebay_templete_content2 { get; set; }
        public string ebay_templete_top { get; set; }
        public string ebay_templete_info { get; set; }
        public Nullable<bool> is_system { get; set; }
        public string ebay_code { get; set; }
        public Nullable<decimal> ebay_price { get; set; }
        public Nullable<System.DateTime> ebay_publish_date { get; set; }
        public Nullable<int> lu_sku { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> last_regdate { get; set; }
    }
}
