//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_store
    {
        public int id { get; set; }
        public string ebay_store_comment { get; set; }
        public string ebay_code { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> is_modify_price { get; set; }
        public Nullable<sbyte> ebay_store_type { get; set; }
        public Nullable<bool> is_templete { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> last_regdate { get; set; }
        public Nullable<int> lu_ebay_sku { get; set; }
    }
}
