//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_system_group_parts
    {
        public int Id { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public string price { get; set; }
        public Nullable<decimal> product_current_cost { get; set; }
        public string ltd_stock { get; set; }
        public string product_name { get; set; }
        public Nullable<int> part_group_id { get; set; }
    }
}
