//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_system_modify_backup
    {
        public int Id { get; set; }
        public int SystemSku { get; set; }
        public int PartSku { get; set; }
        public string Batch { get; set; }
        public decimal Cost { get; set; }
        public decimal SystemPrice { get; set; }
        public System.DateTime Regdate { get; set; }
    }
}
