//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_system_parts_history
    {
        public int id { get; set; }
        public string parent_id { get; set; }
        public Nullable<int> system_sku { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public Nullable<int> comment_id { get; set; }
        public string comment_name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> part_quantity { get; set; }
        public Nullable<int> max_quantity { get; set; }
        public string compatibility_parts { get; set; }
        public Nullable<int> part_group_id { get; set; }
        public Nullable<bool> is_online { get; set; }
        public Nullable<bool> is_label_of_flash { get; set; }
        public System.DateTime regdate { get; set; }
        public string ebay_itemid { get; set; }
    }
}
