//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_store_templete
    {
        public int id { get; set; }
        public Nullable<int> ebay_templete_id { get; set; }
        public string ebay_templete_comment { get; set; }
        public string ebay_templete_content { get; set; }
        public string ebay_templete_top { get; set; }
        public string ebay_templete_info { get; set; }
        public string ebay_templete_after_filter { get; set; }
        public Nullable<int> ebay_store_id { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> last_regdate { get; set; }
    }
}
