//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_ebay_shipping_settings
    {
        public int ID { get; set; }
        public Nullable<decimal> shippingFee { get; set; }
        public string shippingCompany { get; set; }
        public Nullable<bool> IsFree { get; set; }
        public string CategoryID { get; set; }
        public string ShortCategoryName { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
