//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_ebay_system_part_comment
    {
        public int id { get; set; }
        public string comment { get; set; }
        public string category_ids { get; set; }
        public Nullable<bool> is_case { get; set; }
        public Nullable<bool> is_cpu { get; set; }
        public Nullable<bool> is_lcd { get; set; }
        public Nullable<bool> is_mb { get; set; }
        public Nullable<bool> is_video { get; set; }
        public Nullable<bool> is_audio { get; set; }
        public Nullable<bool> is_network { get; set; }
        public Nullable<bool> is_cpu_fan { get; set; }
        public Nullable<int> max_quantity { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<bool> showit { get; set; }
        public Nullable<decimal> append_charge { get; set; }
        public Nullable<int> section { get; set; }
        public string e_field_name { get; set; }
        public Nullable<bool> eBayShowit { get; set; }
        public Nullable<int> defaultPartGroupId { get; set; }
    }
}
