//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_system_item_specifics
    {
        public int id { get; set; }
        public int system_sku { get; set; }
        public string ItemSpecificsName { get; set; }
        public string ItemSpecificsValue { get; set; }
    }
}
