//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_email_history
    {
        public int serial_no { get; set; }
        public string email_to { get; set; }
        public string email_subject { get; set; }
        public string email_body { get; set; }
        public Nullable<System.DateTime> email_create_datetime { get; set; }
        public Nullable<int> staff_serial_no { get; set; }
        public Nullable<int> system_category_serial_no { get; set; }
    }
}
