//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_selling_tmp_db
    {
        public int id { get; set; }
        public Nullable<decimal> BuyItNowPrice { get; set; }
        public string BuyItNowPrice_currencyID { get; set; }
        public string ItemID { get; set; }
        public string ListingDetails_StartTime { get; set; }
        public string ListingDetails_ViewItemURL { get; set; }
        public string ListingDetails_ViewItemURLForNaturalSearch { get; set; }
        public string ListingType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> SellingStatus_CurrentPrice { get; set; }
        public string SellingStatus_CurrentPrice_currencyID { get; set; }
        public Nullable<decimal> ShippingDetails_ShippingServiceCost { get; set; }
        public string TimeLeft { get; set; }
        public string Title { get; set; }
        public Nullable<int> WatchCount { get; set; }
        public Nullable<int> QuantityAvailable { get; set; }
        public string SKU { get; set; }
        public string PictureDetails_GalleryURL { get; set; }
        public Nullable<decimal> ClassifiedAdPayPerLeadFee { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public Nullable<int> sys_sku { get; set; }
    }
}
