//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ebay_item_number
    {
        public int id { get; set; }
        public string item_number { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public string luc_type { get; set; }
    }
}
