//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_ebay_system_history
    {
        public int id { get; set; }
        public string sys_sku { get; set; }
        public Nullable<int> category_id { get; set; }
        public string ebay_system_name { get; set; }
        public string ebay_subtitle { get; set; }
        public Nullable<decimal> ebay_system_price { get; set; }
        public string ebay_system_current_number { get; set; }
        public Nullable<decimal> selected_ebay_sell { get; set; }
        public Nullable<decimal> no_selected_ebay_sell { get; set; }
        public Nullable<bool> is_include_shipping { get; set; }
        public Nullable<bool> showit { get; set; }
        public Nullable<int> view_count { get; set; }
        public string logo_filenames { get; set; }
        public string keywords { get; set; }
        public string system_title1 { get; set; }
        public string system_title2 { get; set; }
        public string system_title3 { get; set; }
        public string cutom_label { get; set; }
        public string main_comment_ids { get; set; }
        public Nullable<bool> is_issue { get; set; }
        public string large_pic_name { get; set; }
        public Nullable<bool> is_from_ebay { get; set; }
        public Nullable<decimal> adjustment { get; set; }
        public Nullable<int> source_code { get; set; }
        public Nullable<bool> is_online { get; set; }
        public Nullable<bool> is_disable_flash_customize { get; set; }
        public System.DateTime regdate { get; set; }
        public string ebay_itemid { get; set; }
    }
}
