//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_ebay_system_group_parts
    {
        public int Id { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public string price { get; set; }
        public Nullable<decimal> product_current_cost { get; set; }
        public string ltd_stock { get; set; }
        public string product_name { get; set; }
        public Nullable<int> part_group_id { get; set; }
    }
}
