//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_ebay_templete
    {
        public int id { get; set; }
        public string templete_comment { get; set; }
        public string templete_content { get; set; }
        public string templete_content2 { get; set; }
        public string templete_info { get; set; }
        public string templete_top { get; set; }
        public Nullable<bool> templete_type { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<System.DateTime> last_regdate { get; set; }
        public string comment { get; set; }
        public string templete_summ_1 { get; set; }
        public string templete_summ_2 { get; set; }
    }
}
