//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_ebay_promotional_sale_details
    {
        public int Id { get; set; }
        public string SaleID { get; set; }
        public string SaleName { get; set; }
        public string SaleItemID { get; set; }
        public string Status { get; set; }
        public string DiscountType { get; set; }
        public decimal DiscountValue { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string SaleType { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
