//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_free_back
    {
        public int free_back_serial_no { get; set; }
        public string free_back_title { get; set; }
        public string free_back_body { get; set; }
        public string free_back_author { get; set; }
        public Nullable<System.DateTime> free_back_create_date { get; set; }
        public Nullable<int> staff_serial_no { get; set; }
        public Nullable<int> free_back_parent_serial_no { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public Nullable<int> system_category_serial_no { get; set; }
        public string feedback_first_name { get; set; }
        public string feedback_last_name { get; set; }
        public string feedback_phone { get; set; }
        public string feedback_ext_code { get; set; }
    }
}
