//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_login_log
    {
        public int login_log_serial_no { get; set; }
        public string remote_address { get; set; }
        public Nullable<System.DateTime> login_datetime { get; set; }
        public Nullable<System.DateTime> logout_datetime { get; set; }
        public Nullable<int> login_name { get; set; }
        public string login_log_category { get; set; }
        public string http_user_agent { get; set; }
    }
}
