//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_menu
    {
        public int menu_child_serial_no { get; set; }
        public string menu_child_name { get; set; }
        public string menu_child_href { get; set; }
        public Nullable<sbyte> menu_is_exist_sub { get; set; }
        public Nullable<int> menu_parent_serial_no { get; set; }
        public Nullable<int> menu_pre_serial_no { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public Nullable<int> menu_child_order { get; set; }
        public Nullable<int> old_db_id { get; set; }
        public string target { get; set; }
    }
}
