//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_modify_price_history
    {
        public int id { get; set; }
        public Nullable<int> lu_part_id { get; set; }
        public Nullable<decimal> lu_price { get; set; }
        public Nullable<decimal> lu_price_discount { get; set; }
        public Nullable<decimal> lu_rebate_price { get; set; }
        public Nullable<decimal> lu_new_price { get; set; }
        public Nullable<decimal> etc_price { get; set; }
        public Nullable<System.DateTime> load_date { get; set; }
        public Nullable<int> etc_part_id { get; set; }
    }
}
