//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_menu_parent
    {
        public int menu_parent_serial_no { get; set; }
        public string menu_parent_name { get; set; }
        public string menu_parent_href { get; set; }
        public Nullable<sbyte> menu_parent_order { get; set; }
    }
}
