//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_news
    {
        public int news_serial_no { get; set; }
        public string news_title { get; set; }
        public string news_body { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public Nullable<int> staff_serial_no { get; set; }
        public Nullable<sbyte> system_category_serial_no { get; set; }
        public Nullable<System.DateTime> news_create_datetime { get; set; }
    }
}
