//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_other_inc_match_lu_sku
    {
        public int id { get; set; }
        public Nullable<int> lu_sku { get; set; }
        public string other_inc_sku { get; set; }
        public Nullable<int> other_inc_type { get; set; }
        public string tmp { get; set; }
        public Nullable<bool> is_have_info { get; set; }
        public string prodType { get; set; }
    }
}
