//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_paypal_send_info
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
        public string Content { get; set; }
        public Nullable<int> OrderCode { get; set; }
    }
}
