//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_order_total_month
    {
        public int id { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public string M { get; set; }
        public Nullable<int> C { get; set; }
        public Nullable<decimal> pre_grand_total { get; set; }
        public string pre_M { get; set; }
        public Nullable<int> pre_C { get; set; }
        public Nullable<decimal> eBayGrandTotal { get; set; }
        public Nullable<int> eBayC { get; set; }
        public Nullable<decimal> Pre_eBayGrandTotal { get; set; }
        public Nullable<int> Pre_eBayC { get; set; }
    }
}
