//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_order_paypal_paymentinfo
    {
        public int Id { get; set; }
        public System.DateTime Regdate { get; set; }
        public int OrderCode { get; set; }
        public string Transaction_Id { get; set; }
        public string Transaction_Type { get; set; }
        public string Payment_Status { get; set; }
        public string Payment_Type { get; set; }
        public string Payment_Total_Amount { get; set; }
    }
}
