//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_order_paypal_record_info
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string card_type { get; set; }
        public string card_number { get; set; }
        public string expiration_date { get; set; }
        public string card_verification_number { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip_code { get; set; }
        public string country { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string amount_unit { get; set; }
        public Nullable<int> order_code { get; set; }
        public string code { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
