//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_order_pay_record
    {
        public int id { get; set; }
        public Nullable<int> order_code { get; set; }
        public Nullable<int> pay_record_id { get; set; }
        public Nullable<System.DateTime> pay_regdate { get; set; }
        public Nullable<decimal> pay_cash { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<decimal> balance { get; set; }
    }
}
