//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_other_inc_synnex
    {
        public int id { get; set; }
        public int luc_sku { get; set; }
        public string sku { get; set; }
        public decimal price { get; set; }
        public string mfp { get; set; }
        public string upc { get; set; }
        public int quantity { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
