//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_invoice_temp_2008
    {
        public int id { get; set; }
        public Nullable<int> invoice { get; set; }
        public string date { get; set; }
        public string first_name { get; set; }
        public string province { get; set; }
        public string taxSta { get; set; }
        public Nullable<decimal> gross { get; set; }
        public Nullable<decimal> sum_of_gst { get; set; }
        public Nullable<decimal> sum_of_pst { get; set; }
        public Nullable<decimal> netsales { get; set; }
    }
}
