//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_order_pay_status
    {
        public int id { get; set; }
        public string order_pay_status_name { get; set; }
        public string order_pay_status_short_name { get; set; }
        public Nullable<bool> tag { get; set; }
    }
}
