//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_order_product
    {
        public int serial_no { get; set; }
        public string order_code { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<int> order_product_sum { get; set; }
        public Nullable<decimal> order_product_price { get; set; }
        public sbyte tag { get; set; }
        public Nullable<decimal> order_product_cost { get; set; }
        public string sku { get; set; }
        public Nullable<int> menu_child_serial_no { get; set; }
        public Nullable<int> menu_pre_serial_no { get; set; }
        public Nullable<int> product_type { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> old_price { get; set; }
        public Nullable<decimal> order_product_sold { get; set; }
        public Nullable<decimal> save_price { get; set; }
        public string product_type_name { get; set; }
        public Nullable<bool> is_old { get; set; }
        public Nullable<decimal> product_current_price_rate { get; set; }
        public string ebayItemID { get; set; }
        public string prodType { get; set; }
    }
}
