//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_product_temp
    {
        public int serial_no { get; set; }
        public Nullable<int> order_serial_no { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<int> order_product_sum { get; set; }
        public Nullable<float> order_product_price { get; set; }
        public Nullable<int> customer_serial_no { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public string sku { get; set; }
    }
}
