//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_other_inc_bind_price_tmp
    {
        public int id { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<int> category_id { get; set; }
        public string other_inc_sku { get; set; }
        public Nullable<decimal> other_inc_price { get; set; }
        public Nullable<int> other_inc_store_sum { get; set; }
        public Nullable<int> other_inc_id { get; set; }
        public Nullable<decimal> product_current_price { get; set; }
        public Nullable<decimal> product_current_price_tmp { get; set; }
        public Nullable<decimal> product_current_cost { get; set; }
        public Nullable<int> bind_type { get; set; }
    }
}
