//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_ebay
    {
        public int id { get; set; }
        public int sales_record_number { get; set; }
        public string user_id { get; set; }
        public string buyer_fullname { get; set; }
        public string buyer_phone_number { get; set; }
        public string buyer_email { get; set; }
        public string buyer_address1 { get; set; }
        public string buyer_address2 { get; set; }
        public string buyer_city { get; set; }
        public string buyer_province { get; set; }
        public string buyer_postal_code { get; set; }
        public string buyer_country { get; set; }
        public string item_number { get; set; }
        public string item_title { get; set; }
        public string custom_label { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public string sale_price_unit { get; set; }
        public Nullable<decimal> shipping_and_handling { get; set; }
        public string shipping_and_handling_unit { get; set; }
        public Nullable<decimal> insurance { get; set; }
        public string insurance_unit { get; set; }
        public Nullable<decimal> cash_on_delivery_fee { get; set; }
        public string cash_on_delivery_fee_unit { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public string total_price_unit { get; set; }
        public string payment_method { get; set; }
        public Nullable<System.DateTime> sale_date { get; set; }
        public Nullable<System.DateTime> checkout_date { get; set; }
        public Nullable<System.DateTime> paid_on_date { get; set; }
        public Nullable<System.DateTime> shipped_on_date { get; set; }
        public string feedback_left { get; set; }
        public string feedback_received { get; set; }
        public string notes_to_yourself { get; set; }
        public string paypal_transaction_id { get; set; }
        public string shipping_service { get; set; }
        public string cash_on_delivery_option { get; set; }
        public string transaction_id { get; set; }
        public string order_id { get; set; }
        public Nullable<int> order_code { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
