//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_order_product_sys_detail
    {
        public int sys_tmp_detail { get; set; }
        public string sys_tmp_code { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public string product_name { get; set; }
        public string cate_name { get; set; }
        public Nullable<int> part_quantity { get; set; }
        public Nullable<int> part_max_quantity { get; set; }
        public Nullable<decimal> product_current_price { get; set; }
        public Nullable<decimal> product_current_cost { get; set; }
        public Nullable<int> product_order { get; set; }
        public Nullable<int> system_templete_serial_no { get; set; }
        public Nullable<int> system_product_serial_no { get; set; }
        public Nullable<int> part_group_id { get; set; }
        public Nullable<decimal> save_price { get; set; }
        public Nullable<decimal> old_price { get; set; }
        public Nullable<int> re_sys_tmp_detail { get; set; }
        public Nullable<decimal> product_current_price_rate { get; set; }
        public Nullable<decimal> product_current_sold { get; set; }
        public Nullable<bool> is_lock { get; set; }
        public string ebay_number { get; set; }
    }
}
