//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_order_facture_state
    {
        public int order_facture_state_serial_no { get; set; }
        public string order_code { get; set; }
        public Nullable<int> facture_state_serial_no { get; set; }
        public Nullable<System.DateTime> order_facture_state_create_date { get; set; }
        public string order_facture_note { get; set; }
    }
}
