//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_on_sale_history
    {
        public int serial_no { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<System.DateTime> begin_datetime { get; set; }
        public Nullable<System.DateTime> end_datetime { get; set; }
        public Nullable<decimal> save_price { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> sale_price { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> modify_datetime { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
    }
}
