//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_order_assigned_to
    {
        public int assigned_to_id { get; set; }
        public string assigned_to_staff_name { get; set; }
        public Nullable<int> assigned_to_staff_id { get; set; }
        public string assigned_to_comment { get; set; }
        public Nullable<int> edit_staff_id { get; set; }
        public string eidt_staff_name { get; set; }
        public Nullable<int> order_code { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
