//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_category_keyword_sub
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string keyword { get; set; }
        public Nullable<bool> showit { get; set; }
        public Nullable<int> priority { get; set; }
        public bool IsShowOnWebPage { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
