//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_pay_method_new
    {
        public int pay_method_serial_no { get; set; }
        public string pay_method_name { get; set; }
        public string pay_check_path_new { get; set; }
        public string pay_check_path { get; set; }
        public Nullable<int> taxis { get; set; }
        public string pay_method_short_name { get; set; }
        public Nullable<bool> tag { get; set; }
        public Nullable<int> priority { get; set; }
        public string AD { get; set; }
        public Nullable<bool> is_card { get; set; }
        public string supper_country { get; set; }
    }
}
