//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_shipping_fee
    {
        public int prod_shipping_fee_id { get; set; }
        public Nullable<int> prod_Sku { get; set; }
        public Nullable<bool> is_system { get; set; }
        public Nullable<decimal> shipping_fee_us { get; set; }
        public Nullable<decimal> shipping_fee_ca { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
