//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_part_group_detail
    {
        public int part_group_detail_id { get; set; }
        public Nullable<int> part_group_id { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<sbyte> showit { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> nominate { get; set; }
    }
}
