//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_page_error_info
    {
        public int id { get; set; }
        public string error_type { get; set; }
        public string email_address { get; set; }
        public string content { get; set; }
        public string luc_sku { get; set; }
        public Nullable<int> category_id { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
