//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_product_shipping_fee
    {
        public int prod_shipping_fee_id { get; set; }
        public Nullable<int> prod_Sku { get; set; }
        public Nullable<bool> is_system { get; set; }
        public Nullable<decimal> shipping_fee_us { get; set; }
        public Nullable<decimal> shipping_fee_ca { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
