//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_detail
    {
        public int product_detail_serial_no { get; set; }
        public Nullable<int> product_in_serial_no { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<int> purchase_serial_no { get; set; }
        public Nullable<sbyte> product_detail_is_sale { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public Nullable<System.DateTime> product_detail_create_date { get; set; }
        public string product_sn { get; set; }
        public Nullable<System.DateTime> sale_create_date { get; set; }
    }
}
