//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pay
    {
        public int pay_serial_no { get; set; }
        public Nullable<int> order_serial_no { get; set; }
        public Nullable<float> pay_amount { get; set; }
        public Nullable<float> pay_balance { get; set; }
        public string pay_method { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public Nullable<int> pay_sales_person { get; set; }
        public string pay_note { get; set; }
        public Nullable<int> tag { get; set; }
    }
}
