//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_part_cate_view_count
    {
        public int id { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> view_count { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
