//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_part_relation_motherboard_video_audio_port
    {
        public int id { get; set; }
        public Nullable<int> mb_sku { get; set; }
        public Nullable<int> video_sku { get; set; }
        public Nullable<int> audio_sku { get; set; }
        public Nullable<int> port_sku { get; set; }
        public Nullable<int> network_sku { get; set; }
        public System.DateTime regdate { get; set; }
    }
}
