//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_product_in
    {
        public int product_in_serial_no { get; set; }
        public Nullable<float> product_in_cost { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<System.DateTime> product_in_date { get; set; }
        public string purchase_serial_no { get; set; }
        public Nullable<int> product_in_staff { get; set; }
        public Nullable<float> product_in_price { get; set; }
        public Nullable<int> product_in_sum { get; set; }
        public Nullable<System.DateTime> product_in_end_date { get; set; }
        public Nullable<float> tag { get; set; }
        public string product_sns { get; set; }
        public Nullable<int> system_category_serial_no { get; set; }
        public Nullable<int> vendor_serial_no { get; set; }
    }
}
