//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_product_detail
    {
        public int product_detail_serial_no { get; set; }
        public Nullable<int> product_in_serial_no { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<int> purchase_serial_no { get; set; }
        public Nullable<sbyte> product_detail_is_sale { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public Nullable<System.DateTime> product_detail_create_date { get; set; }
        public string product_sn { get; set; }
        public Nullable<System.DateTime> sale_create_date { get; set; }
    }
}
