//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_part_group_detail
    {
        public int part_group_detail_id { get; set; }
        public Nullable<int> part_group_id { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<sbyte> showit { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> nominate { get; set; }
    }
}
