//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_store_sum
    {
        public int id { get; set; }
        public string product_serial_no { get; set; }
        public Nullable<int> product_store_category { get; set; }
        public Nullable<int> product_store_sum { get; set; }
        public string manufacturer_part_number { get; set; }
        public Nullable<decimal> product_cost { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<int> lu_sku { get; set; }
        public string product_name { get; set; }
        public Nullable<bool> tag { get; set; }
    }
}
