//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_category
    {
        public int menu_child_serial_no { get; set; }
        public string menu_child_name { get; set; }
        public string menu_child_name_logogram { get; set; }
        public string menu_child_href { get; set; }
        public Nullable<sbyte> menu_is_exist_sub { get; set; }
        public Nullable<int> menu_parent_serial_no { get; set; }
        public Nullable<int> menu_pre_serial_no { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public Nullable<int> menu_child_order { get; set; }
        public Nullable<int> old_db_id { get; set; }
        public string menu_child_name_f { get; set; }
        public Nullable<sbyte> page_category { get; set; }
        public Nullable<sbyte> is_noebook { get; set; }
        public Nullable<bool> export { get; set; }
        public Nullable<bool> is_display_stock { get; set; }
        public Nullable<bool> is_virtual { get; set; }
        public Nullable<int> view_count { get; set; }
        public string keywords { get; set; }
        public string keywords_cates { get; set; }
        public Nullable<bool> is_view_stock_filter { get; set; }
        public Nullable<bool> is_view_menu { get; set; }
        public Nullable<System.DateTime> update_price_date { get; set; }
        public Nullable<bool> valid { get; set; }
        public string eBayCategoryID { get; set; }
        public string ebayStoreCategoryID_1 { get; set; }
        public string ebayStoreCategoryID_2 { get; set; }
        public Nullable<bool> is_left_view { get; set; }
        public string font_name { get; set; }
    }
}
