//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_product_collection
    {
        public int product_collection_id { get; set; }
        public string product_collections { get; set; }
        public string product_collection_topic { get; set; }
        public Nullable<int> product_collection_redirect_path_type { get; set; }
        public string product_collection_title { get; set; }
        public string product_collection_title_path { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
