//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_store_sum
    {
        public int id { get; set; }
        public string product_serial_no { get; set; }
        public Nullable<int> product_store_category { get; set; }
        public Nullable<int> product_store_sum { get; set; }
        public string manufacturer_part_number { get; set; }
        public Nullable<decimal> product_cost { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<int> lu_sku { get; set; }
        public string product_name { get; set; }
        public Nullable<bool> tag { get; set; }
    }
}
