//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pre_status
    {
        public int pre_status_serial_no { get; set; }
        public string pre_status_name { get; set; }
        public Nullable<bool> showit { get; set; }
        public Nullable<int> priority { get; set; }
        public string back_color { get; set; }
        public Nullable<bool> view_invoice { get; set; }
        public string AD { get; set; }
    }
}
