//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_compatibility
    {
        public int serial_no { get; set; }
        public Nullable<int> main_product { get; set; }
        public Nullable<int> accessories_menu_child { get; set; }
    }
}
