//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_purchase
    {
        public int purchase_serial_no { get; set; }
        public string purchase_invoice { get; set; }
        public string purchase_net_amount { get; set; }
        public string purchase_gst { get; set; }
        public string purchase_pst { get; set; }
        public string purchase_paid_amount { get; set; }
        public string purchase_check_no { get; set; }
        public string purchase_bank { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public string purchase_note { get; set; }
        public Nullable<int> vendor_serial_no { get; set; }
        public string staff_serial_no { get; set; }
        public Nullable<int> system_category_serial_no { get; set; }
        public string purchase_product_list { get; set; }
    }
}
