//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_product_import_price
    {
        public int id { get; set; }
        public string other_inc_name { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public Nullable<decimal> part_real_cost { get; set; }
        public Nullable<decimal> part_sell { get; set; }
        public Nullable<System.DateTime> part_real_regdate { get; set; }
        public string part_name { get; set; }
        public Nullable<int> part_quantity { get; set; }
        public string vendor_invoice { get; set; }
        public string order_codes { get; set; }
        public Nullable<bool> is_order { get; set; }
        public string note { get; set; }
    }
}
