//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_product_size
    {
        public int product_size_id { get; set; }
        public string product_size_name { get; set; }
        public Nullable<decimal> begin_price { get; set; }
        public Nullable<decimal> end_price { get; set; }
        public Nullable<int> product_type { get; set; }
    }
}
