//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_product_price_history
    {
        public int id { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public string regdateText { get; set; }
    }
}
