//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_pre_index_page_setting
    {
        public int id { get; set; }
        public Nullable<int> sku { get; set; }
        public Nullable<bool> Isys { get; set; }
        public Nullable<int> CateId { get; set; }
        public Nullable<int> priority { get; set; }
        public string title { get; set; }
        public string LCDImage { get; set; }
        public Nullable<int> lcd_p_X { get; set; }
        public Nullable<int> lcd_p_Y { get; set; }
        public Nullable<int> case_p_X { get; set; }
        public Nullable<int> case_p_Y { get; set; }
    }
}
