//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_product_out
    {
        public int product_out_serial_no { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<System.DateTime> product_out_date { get; set; }
        public Nullable<int> product_out_sale_staff { get; set; }
        public Nullable<int> product_out_staff { get; set; }
        public Nullable<System.DateTime> product_out_end_date { get; set; }
        public Nullable<decimal> product_detail_out_price { get; set; }
        public Nullable<int> product_out_client { get; set; }
        public string product_out_receipt { get; set; }
        public Nullable<int> system_category_serial_no { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public string product_sn { get; set; }
    }
}
