//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_product_price_tmp
    {
        public int id { get; set; }
        public Nullable<decimal> curr_change_cost { get; set; }
        public Nullable<decimal> curr_change_price { get; set; }
        public string curr_change_ltd { get; set; }
        public Nullable<int> curr_change_quantity { get; set; }
        public string curr_change_regdate { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public Nullable<bool> is_auto_change { get; set; }
    }
}
