//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_rival_store
    {
        public int rival_id { get; set; }
        public Nullable<int> rival_ltd_id { get; set; }
        public string rival_sku { get; set; }
        public string rival_manufacture_code { get; set; }
        public string rival_part_name { get; set; }
        public Nullable<decimal> rival_price { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
    }
}
