//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_right
    {
        public int right_id { get; set; }
        public string right_content { get; set; }
        public string right_page { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public string left_content { get; set; }
        public string main_content { get; set; }
        public Nullable<int> part_product_category { get; set; }
        public Nullable<bool> exist_top { get; set; }
    }
}
