//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_right
    {
        public int right_id { get; set; }
        public string right_content { get; set; }
        public string right_page { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public string left_content { get; set; }
        public string main_content { get; set; }
        public Nullable<int> part_product_category { get; set; }
        public Nullable<bool> exist_top { get; set; }
    }
}
