//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_split_line
    {
        public int split_line { get; set; }
        public string split_line_name { get; set; }
        public Nullable<int> line_order { get; set; }
        public Nullable<int> menu_child_serial_no { get; set; }
    }
}
