//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_system_product
    {
        public int system_product_serial_no { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<int> system_templete_serial_no { get; set; }
        public Nullable<int> product_order { get; set; }
        public Nullable<sbyte> showit { get; set; }
        public Nullable<int> part_quantity { get; set; }
        public Nullable<int> part_max_quantity { get; set; }
        public Nullable<int> part_group_id { get; set; }
        public Nullable<bool> is_exce_add { get; set; }
    }
}
