//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_system_configure_category
    {
        public int system_configure_category_serial_no { get; set; }
        public string menu_child_list { get; set; }
        public string system_configure_category_name { get; set; }
    }
}
