//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_supercom_store_2
    {
        public int id { get; set; }
        public string f0 { get; set; }
        public string f1 { get; set; }
        public string f2 { get; set; }
        public string f3 { get; set; }
        public string f4 { get; set; }
        public string f5 { get; set; }
        public string f6 { get; set; }
        public string f7 { get; set; }
        public string f8 { get; set; }
        public string f9 { get; set; }
        public string f10 { get; set; }
        public string f11 { get; set; }
        public string f12 { get; set; }
        public string f13 { get; set; }
        public string f14 { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<int> luc_sku { get; set; }
        public string prodType { get; set; }
    }
}
