//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sp_tmp
    {
        public int sys_tmp_serial_no { get; set; }
        public string sys_tmp_code { get; set; }
        public Nullable<decimal> sys_tmp_price { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public string ip { get; set; }
        public Nullable<int> system_templete_serial_no { get; set; }
        public string email { get; set; }
        public Nullable<sbyte> system_category_serial_no { get; set; }
        public Nullable<sbyte> is_noebook { get; set; }
        public Nullable<decimal> sys_tmp_cost { get; set; }
        public string sys_tmp_product_name { get; set; }
        public Nullable<decimal> save_price { get; set; }
        public Nullable<decimal> old_price { get; set; }
        public Nullable<bool> is_old { get; set; }
        public Nullable<int> old_part_id { get; set; }
        public Nullable<decimal> syst_tmp_price_rate { get; set; }
        public Nullable<bool> is_customize { get; set; }
        public Nullable<bool> is_templete { get; set; }
        public string price_unit { get; set; }
        public string ebay_number { get; set; }
        public Nullable<bool> is_modify { get; set; }
    }
}
