//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_staff
    {
        public int staff_serial_no { get; set; }
        public string staff_login_name { get; set; }
        public string staff_email { get; set; }
        public string staff_phone { get; set; }
        public Nullable<bool> tag { get; set; }
        public string staff_password { get; set; }
        public string staff_realname { get; set; }
        public Nullable<System.DateTime> staff_last_login_date { get; set; }
        public string staff_system_category { get; set; }
        public Nullable<bool> staff_type { get; set; }
    }
}
