//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_shipping_company
    {
        public int shipping_company_id { get; set; }
        public string shipping_company_name { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> system_category { get; set; }
        public Nullable<bool> is_sales_promotion { get; set; }
        public Nullable<decimal> default_charge { get; set; }
        public Nullable<bool> showit { get; set; }
        public Nullable<bool> is_ebay { get; set; }
    }
}
