//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_system_templete_category
    {
        public int system_templete_category_serial_no { get; set; }
        public string system_templete_category_name { get; set; }
        public Nullable<int> system_templete_category_order { get; set; }
        public Nullable<sbyte> tag { get; set; }
        public Nullable<int> old_db_id { get; set; }
        public Nullable<sbyte> is_exist_sub { get; set; }
        public string system_templete_category_name_f { get; set; }
    }
}
