//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_track
    {
        public int track_id { get; set; }
        public Nullable<System.DateTime> track_regdate { get; set; }
        public string track_comment { get; set; }
        public Nullable<int> track_staff_id { get; set; }
        public string track_url { get; set; }
        public string track_ip { get; set; }
        public Nullable<int> track_type_id { get; set; }
    }
}
