//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_update_product_cost_history
    {
        public int product_cost_history_id { get; set; }
        public Nullable<int> product_serial_no { get; set; }
        public Nullable<decimal> product_cost { get; set; }
        public string product_factory_sku { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public Nullable<int> staff_id { get; set; }
    }
}
