//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_update_table_fields
    {
        public int update_table_field_id { get; set; }
        public string update_field_comment { get; set; }
        public string update_table_field_name { get; set; }
        public string update_table_name { get; set; }
    }
}
