//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_update_relation
    {
        public int update_relation_id { get; set; }
        public string update_relation_table_a { get; set; }
        public string update_relation_table_a_fields { get; set; }
        public string update_relation_table_b { get; set; }
        public string update_relation_table_b_fields { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> regdate { get; set; }
        public string update_relation_table_a_fields_comment { get; set; }
        public string update_relation_table_b_fields_comment { get; set; }
    }
}
