//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class tb_update_product_store
    {
        public int update_store_id { get; set; }
        public string update_store_regdate { get; set; }
        public Nullable<int> update_store_staff { get; set; }
        public string a { get; set; }
        public string b { get; set; }
        public string c { get; set; }
        public string d { get; set; }
        public string e { get; set; }
        public string f { get; set; }
        public string g { get; set; }
        public string h { get; set; }
        public string i { get; set; }
        public string j { get; set; }
        public string k { get; set; }
        public string l { get; set; }
        public string m { get; set; }
        public string n { get; set; }
        public string o { get; set; }
        public string p { get; set; }
        public string q { get; set; }
    }
}
