//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user_token
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.Guid Token { get; set; }
        public System.DateTime Regdate { get; set; }
        public int UserType { get; set; }
        public System.DateTime Expired { get; set; }
        public string SysCountry { get; set; }
        public Nullable<int> CartGoodsQty { get; set; }
    }
}
