//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LU.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user_token
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.Guid Token { get; set; }
        public System.DateTime Regdate { get; set; }
        public int UserType { get; set; }
        public System.DateTime Expired { get; set; }
        public string SysCountry { get; set; }
        public Nullable<int> CartGoodsQty { get; set; }
    }
}
